### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by w33zy** [churchio/onebody#145]
I feel a way asking this feature request on such a great open source project. The thing is, i showed this to friend who is the President of the Youth-fellowship and the two things he asked about are event calendar and community notice board. I am just asking for the event calendar

**Comment by bwhatley87** [comment]
I'm curious if this feature is making any progress. Seems like that'd be a big functionality for drawing in users.

**Comment by notdodgy** [comment]
An interim option could be to allow an embedded frame - this would enable a Google calendar to be shown on a site (there are options on Google calendar for generating the embed code).  
Similar to embedding a map.

**Comment by seven1m** [comment]
Closing for now. This is a big task and probably won't happen in the near term.
