### ISSUE TITLE
Add Custom Fields for People, Families and Groups.

### ISSUE THREAD

**Issue by juddey** [churchio/onebody#179]
## Basic Requirements
* An unlimited number of fields should be supported
* Users should be able to specify the characteristics of these fields
* The fields should be re-orderable on the page
* The following field types should be supported: number, text, date, datetime 
* Anything stored must be able to be reported on (in the new reporting feature :)

## Wireframes
[Guide to interpreting wireframes](https://github.com/churchio/onebody/wiki/How-to-interpret-wireframes)
1.  Admin Page: Allows an administrator to configure the fields to display on the particular page.
2.  People Page: Displays the effect of the admin page. 

![onebody-fields-admin](https://cloud.githubusercontent.com/assets/7445602/3775000/66129398-1939-11e4-8045-88e61d5978b5.png)
![onebody-people](https://cloud.githubusercontent.com/assets/7445602/3775001/6bd459ec-1939-11e4-89a4-3f9ee76fd34c.png)

**Comment by TechWilk** [comment]
Feature sounds great!  Would be useful if `custom_fields` additionally have the option to:
* only allow updates from an admin
* hide fields from users

**Use case / explanation:**
We are legally required (here in the UK) to hold DBS check information for all youth / children's workers, etc. who work with children.  Our admin's would like this to be stored in the directory

I'm thinking it would need two fields:
* Not checked (default) / Pass / Fail / (Expired?) `[pre-defined list]`
* Date of expiry `[date]`

A report could alert the admins when the DBS's need renewing and possibly switch out *Pass* for *Expired*.
For obvious reasons, user's shouldn't be able to update this data themselves!

**Comment by klarkc** [comment]
+1 It could be great.

I gave registration forms to my church members, and I have some custom fields that I must use in the system, for example: emergency number and blood type. Plus, a published field option will be needed too.

**Comment by mounte** [comment]
+1 for this.
We have some legacy database that we would like to migrate and some example fields that we would use custom fields for are date when baptized and location.

**Comment by maymint** [comment]
Hello, I was wondering if this is something that can be worked on as we would really like to implement the functionality soonest. How can we go about finding a developer that is already familiar with this platform even on a paid basis to help implement it please?

**Comment by seven1m** [comment]
@maymint I plan to work on this over the next few weeks, as I have some time off. I'll let you know...

**Comment by amitgds** [comment]
Hello, Can any one share the code of partially completed feature who has worked on this before. Actually I am looking for this feature to implement in to my application. If I will get the partially completed code then may be I can work on this to wrap this feature.

**Comment by maymint** [comment]
Hello @seven1m and @amitgds wondering if anyone has looked any further into this feature and if there is any idea of when it may be available online? many thanks

**Comment by seven1m** [comment]
I'm working it right now actually! I'll keep you posted.

**Comment by seven1m** [comment]
The beginning of custom fields has been added in #636. While it's only on People, it's a good start, and I want to start building smaller, more focused issues/PRs so others can chip in. Closing this larger issue in favor of that approach.
