### ISSUE TITLE
Spanish (Latin America) translation

### ISSUE THREAD

**Issue by abalbin** [churchio/onebody#214]
Hi,

First of all, thanks for the great job you are doing. We want to use this for peruvian churches. So, I'd like to collaborate with spanish (LA) translation. I have an OneSky account with r2d2klapa@gmail.com

**Comment by seven1m** [comment]
Heads up I uploaded new strings to OneSky. OneBody 3.5.0 should be out in a week or so with improved Import functionality, Facebook login, and more.

**Comment by seven1m** [comment]
I'm closing all the translation issues to get our bug list down to something workable. Closing this issue does **not** mean we are not continuing to work on (or encourage work on) translations of OneBody -- it only means that we won't track that progress in an issue (OneSky has a better system for tracking progress). Thanks!
