### ISSUE TITLE
Heroku Deploy Button

### ISSUE THREAD

**Issue by Danielpk** [churchio/onebody#215]
It would be interesting to add a Heroku deploy button at website and project readme.

Check out about it here: https://blog.heroku.com/archives/2014/8/7/heroku-button

**Comment by seven1m** [comment]
#216 is done!

#423 are the changes necessary to make OneBody run on Heroku.

This is gettin' real!

**Comment by seven1m** [comment]
Closing this for the same reason I closed #430.
