### ISSUE TITLE
Feature request: Mobile Apps (Android/iOS)

### ISSUE THREAD

**Issue by ajma** [churchio/onebody#228]
Has there been any requests for mobile apps? This seems like something that would be useful for users. To help make this as easy as possible, I'd suggest using something like cordova so the mobile app would just be a basic native app with a webview and most of the website can be re-used within the app. You could add some other mobile app features like notifications.

**Comment by Sahbum** [comment]
I would be interested in this as well.  We're trying to engage more youth and younger crowd at our church.  Since they tend to be glued to their phones, an app would be great.  Plus we're trying to get a better communications platform going.  I'd love to see some sort of messaging feature that ties to groups in this, along with prayer requests and calendar notification.

**Comment by ajma** [comment]
Sorry, let me try to carve out some time for my prototype. I can prototype it with someone's instance of onebody. @gustavobim or @Sahbum, if you give me your url to your site, I'll create you a sample APK for Android that you can use to try it out.

**Comment by ajma** [comment]
@gustavobim @Sahbum @seven1m do any of you have an Android phone? Give this a try if you do:
https://dl.dropboxusercontent.com/u/6036911/onebody.apk
It'll ask you for your current onebody url.
My plan is to have this generic one published in the appstore, but I'll provide a script or instructions so that people can easily make a custom apk with their own icon and always going directly to their instance of onebody.

at a high level, this is basically an app that just has a giant webview and loads the normal website inside an app. the benefit of this is
- completely reusing everything that's already build for the mobile form-factor
- an actual icon on your phone
- (future) hook into proper push notifications for alerts
- (future) lets users use their camera on phone to post pictures

@seven1m if you like this idea, I've created a repo here: https://github.com/ajma/onebody-android
I'd be glad to move it into the churchio org if you'd like. maybe you can create a "mobile team" and add me in and I'll manage that repo. I'll also create a corresponding iOS one, but i'm less familiar with iOS so it'll take me some time.

**Comment by seven1m** [comment]
Awesome! I don't have an android phone, but I have an older Nexus 7 at home -- I'll give it a try when I'm back from vaca next week!

**Comment by Sahbum** [comment]
I have one.  I will let you know Sunday if it works for me.

**Comment by leannb** [comment]
I've installed it. Seems to work just fine.

**Comment by seven1m** [comment]
There has been some renewed discussion around mobile apps for both iOS and Android in our Slack channel. Please join if you are interested: https://slackin-churchio.herokuapp.com/

**Comment by seven1m** [comment]
I'm going to close this issue. There is still desire for a native-ish mobile app for both iOS and Android, but we don't need this issue here to track that work. Anyone interested in working on the mobile app(s), please hop in our [Slack chat](http://chat.church.io/) and get some conversation going!
