### ISSUE TITLE
Chinese (Simplified) translation

### ISSUE THREAD

**Issue by oppih** [churchio/onebody#247]
Maybe you can invite me into the OneSky translation project ? My email address is letwego28@gmail.com

**Comment by seven1m** [comment]
@oppih are you still working on this? Is there anything I can do to unstick this project?

**Comment by oppih** [comment]
So much words to translate, I'm working on it with a little progress. I wonder if I can invite someone I know to help me with Chinese translation?

**Comment by seven1m** [comment]
Absolutely!! Just let me know their email address and I'll add them to the account.

(You can post their email address here, or you can send it to me at tim@timmorgan.org.)

**Comment by oppih** [comment]
OK, I'll get you the email address when I confirm it.

**Comment by qijunumich** [comment]
Hi, I am a Chinese student major in Computer Science in UMich. Can I join the translation work?

**Comment by oppih** [comment]
@qijunumich You may just send an email to Tim using your email address to get invited to OneSky for the translation.

**Comment by seven1m** [comment]
Yes! I'm a bit behind on responding to email, but will get caught up this weekend. Send me your email address (to `tim@timmorgan.org`) and I'll set you up.

Thanks!

**Comment by seven1m** [comment]
Heads up I uploaded new strings to OneSky. OneBody 3.5.0 should be out in a week or so with improved Import functionality, Facebook login, and more.

**Comment by seven1m** [comment]
I'm closing all the translation issues to get our bug list down to something workable. Closing this issue does **not** mean we are not continuing to work on (or encourage work on) translations of OneBody -- it only means that we won't track that progress in an issue (OneSky has a better system for tracking progress). Thanks!
