### ISSUE TITLE
Known By Name/Nickname

### ISSUE THREAD

**Issue by monty5811** [churchio/onebody#257]
We have quite a lot of people who are known by nicknames in our congregation.

Would it be possible to have an additional "Nickname" or "Known by" field for people to aid in searching.

Perhaps display in brackets after someone's real name?

**Comment by AndyGauge** [comment]
I was going to begin working on this, but when I started to dive into the existing functionality, I'm concerned this is blocked by households.  When I search for a term, my development log states 'concat(people.first_name, ' ', people.last_name) like '%search_term%' or families.name like '%search_term%.  Is it safe to proceed on this feature without the households complete?

**Comment by AndyGauge** [comment]
How does a nickname get added to a member?
1. A field within the profile
2. should this be included in the CSV?

**Comment by AndyGauge** [comment]
I'm setting Person.alias to be approved by admin in the Updater class.  If this is incorrect, please let me know.

Thanks

**Comment by AndyGauge** [comment]
The requirement 'show nickname in brackets after real name' is that everywhere in the site or just the directory?  It would be easy to change the .name method, but that may be too broad of a change.  Here is a proposed direction.  The title of the show person uses the nickname, but the rest of the site preserves the normal name.
![image](https://cloud.githubusercontent.com/assets/6525150/14236207/74fb6c58-f9c6-11e5-964a-0baabde90723.png)

**Comment by AndyGauge** [comment]
![image](https://cloud.githubusercontent.com/assets/6525150/14236252/4e9e7aae-f9c7-11e5-959a-71f35ef13b4c.png)
