### ISSUE TITLE
Add Custom Pages

### ISSUE THREAD

**Issue by monty5811** [churchio/onebody#260]
Ability to add more pages through the interface at pages/admin 

First steps towards a CMS?

**Comment by seven1m** [comment]
I like the idea of OneBody someday having more general content management (pages) support, but I'm hesitant to just add ability to create new pages. I think such a feature would need to be accompanied by image uploads and management to be useful, URL slugs, etc. @monty5811 if you would be willing to take the reigns and run with this and also to build the other CMS features at the same time so we can release them together, let's do it!

**Comment by seven1m** [comment]
Closing this as there's little/no interest from anyone in doing it.
