### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by rosko** [churchio/onebody#309]
We are russian-speaking church and we want to use onebody for our community.
How we can translate onebody into russian?

P.S. Thanks for the beautiful tool!

**Comment by seven1m** [comment]
Heads up I uploaded new strings to OneSky. OneBody 3.5.0 should be out in a week or so with improved Import functionality, Facebook login, and more.

**Comment by seven1m** [comment]
I'm closing all the translation issues to get our bug list down to something workable. Closing this issue does **not** mean we are not continuing to work on (or encourage work on) translations of OneBody -- it only means that we won't track that progress in an issue (OneSky has a better system for tracking progress). Thanks!
