### ISSUE TITLE
Appearance settings per site

### ISSUE THREAD

**Issue by stephanvd** [churchio/onebody#316]
Looking to implement custom backgrounds for the login screen. There is not really a fitting place in the admin screen to add this form right now.

I can imagine maybe some more small appearance related settings getting added (logo, header color) sometime.

Should we add an appearance settings screen?

**Comment by seven1m** [comment]
@mattraykowski did you make any progress on this? If so, can you push your code to a branch and let me know what it is? I might like to pick this up and finish it. I think it could be a nice little feature.

**Comment by seven1m** [comment]
Closing this for now.
