### ISSUE TITLE
Explore Twilio Integration

### ISSUE THREAD

**Issue by monty5811** [churchio/onebody#322]
This issue is for discussion of possible Twilio integrations for OneBody.

## Possible use cases:

* Allow for users to sign up to text updates
* Allow churches to send alerts to congregation (eg meeting cancelled at short notice)
* More involved: allow sign up for events by SMS reply
* ....

What other uses are there?

## Requirements:

* Interface with Twilio api
* UI for users to sign up
* UI for sending one off messages?
* For sign up: need to serve TwilML and provide UI for inspecting response
* ...

These probably need to be addressed more fully after the use cases have been established.

## Links:
* [Twilio on Rails – Integrating Twilio With Your Rails 4 App](https://www.twilio.com/blog/2014/02/twilio-on-rails-integrating-twilio-with-your-rails-4-app.html)
* [https://www.twilio.com/blog/2012/02/adding-twilio-sms-messaging-to-your-rails-app.html](https://www.twilio.com/blog/2012/02/adding-twilio-sms-messaging-to-your-rails-app.html)
* [https://github.com/twilio/twilio-ruby](twilio-ruby)
* [https://www.twilio.com/docs/ruby/install](Twilio Docs (Ruby))

**Comment by seven1m** [comment]
:+1: I like this idea. Let's do it! :smiley_cat:

**Comment by hunternet93** [comment]
How about just using email-to-SMS gateways (i.e 1235551234@txt.att.net)? That's free, with the added requirement of knowing each user's cell carrier. Here's a big list: http://www.quertime.com/article/arn-2010-11-04-1-complete-list-of-email-to-sms-gateways/

**Comment by caycehouse** [comment]
You could always try email to SMS gateways, but if a carrier isn't set fall back to twilio integration.

**Comment by seven1m** [comment]
I like this idea, but I don't personally have time to work on it. There is promising new project in the Church.IO community that is working on making it super easy to send SMS messages... check it out! https://github.com/monty5811/apostello

**Comment by coptic-bola** [comment]
I'd be happy to take this on, if we can reopen it.
