### ISSUE TITLE
Add a setting to disable families

### ISSUE THREAD

**Issue by buob** [churchio/onebody#324]
Not that our church doesn't value children, but they don't necessarily need to be on the membership portal.  What are the cons of adding a setting to disable the concept of families?  Is there a technical reason they exist?

**Comment by buob** [comment]
I like the idea of just having the family idea as a data structure (for things like tax purposes) and not necessarily published everywhere. :+1:

**Comment by andrewwippler** [comment]
Isn't this already an option? Children are not visible unless strictly allowed to be visible. 

At least, this is the behavior I see.

**Comment by seven1m** [comment]
I believe this is no longer relevant given #589. Closing for now. (If we see that Households need to be disabled, it can be reopened.)
