### ISSUE TITLE
Add a setting to disable stream

### ISSUE THREAD

**Issue by buob** [churchio/onebody#327]
:dancers:

**Comment by seven1m** [comment]
@buob after thinking about this, I don't think it would be a problem to disable the stream. I suppose the "home" page, in that case, would become the user's own profile page? Let's do this.

**Comment by buob** [comment]
Yeah, sorry about letting this die without answering your question.

For our use case I would say the directory would make the better home page, is that alright with you?

**Comment by seven1m** [comment]
:+1:

**Comment by AndyGauge** [comment]
To use this feature, click the Admin tab on the left.  At the bottom, click settings under configuration.  Click the features tab in site settings and uncheck the Stream option.
