### ISSUE TITLE
Can't Install on Digital Ocean without an SSH Key

### ISSUE THREAD

**Issue by jaschwar** [churchio/onebody#349]
I used the following link, http://installer.71m.us/install?url=https%3A%2F%2Fgithub.com%2Fchurchio%2Fonebody with defaults 1G memory and region as NY 3.

It failed for my four times in the same manner -- failing to install mysql.

Please help me in recovering or make changes so this will work.

Here is screen shot of console:
![onebodyinstallfail](https://cloud.githubusercontent.com/assets/3407614/5263805/4336f212-7a03-11e4-8302-ebd82f431cd0.png)

**Comment by bonpixel** [comment]
+1 for didn't work w/o ssh key, works with ssh key.

Thanks for the help!

**Comment by theskyfloor** [comment]
Can y'all give me tip on this... I have SSH keys installed on my DO account but it still won't let me install using the tool - says that the user OneBody doesn't have access to the key... which makes sense how could it if the Droplet is new?

**Comment by theskyfloor** [comment]
I just installed it manually. It was far easier than the one click installer :  (

**Comment by seven1m** [comment]
I've opened an support issue with DigitalOcean. They were able to reproduce this problem with a simple CloudConfig of just:

```yaml
#cloud-config
packages:
- mysql-server
```

They're investigating further at this time.

**Comment by seven1m** [comment]
DigitalOcean gave me this response:

> Our engineers looked into this and have discovered the problem is due to the requirement to change your root password on first login when using a password over a SSH key. We came up with a work around of setting the root password in the cloud-config
>
> We're working on finding a better answer for you but someone else in our community has found this problem as well - https://www.digitalocean.com/community/questions/forcing-to-change-password-when-using-api

**Comment by seven1m** [comment]
I changed the installer so it now does a ahead-of-time fail with a helpful error message if the DO account has no SSH keys. The error page also gives links to guides showing the user how to add an SSH key to their account.

I think this is the best we can do given that an SSH key is absolutely required.

**Comment by khebbie** [comment]
Hello!

 

You have a new message, please read <http://kcsr.ba/peasant.php?cepb>

 

klaus@hebsgaard.dk

**Comment by khebbie** [comment]
Hello!

 

You have a new message, please read <http://myphamchatluong.info/cost.php?4yl>

 

klaus@hebsgaard.dk
