### ISSUE TITLE
German Translation

### ISSUE THREAD

**Issue by metaxy** [churchio/onebody#350]
We started to translate onebody into german via http://churchio.oneskyapp.com/collaboration/project?id=11209 .
We are not done yet, but is it possible to use what we already translated? Or do we have to wait for version 3.3?

**Comment by metaxy** [comment]
how long will it take, so we may know when we can start using it?

**Comment by seven1m** [comment]
Sorry about that! I just updated the translation and updated the demo site at http://onebody.71m.us. I created a user account for you there with the email `m*****@w*****.name` and sent you an account verification email to set your password.

Let me know if you need anything else, and thank you for your work on OneBody!!!!
