### ISSUE TITLE
Meta-church features

### ISSUE THREAD

**Issue by remocrevo** [churchio/onebody#358]
I would to empower neighboring congregations to work together more, specifically on a city-wide level.  I considered just installing OneBody for my city and inviting everyone to join, and that might still be a good solution.  However, I wanted to know if others had considered building in the ability for various "neighboring" OneBody installations to communicate (based on locale, church "group", etc.).  This would allow things like city-wide events, prayer requests, member map, everything!  Not sure if it would work best as a separate meta site that gets sync'ed, or simply a "my city" view of any installation that pulls in data from other sites.  There could be appropriate privacy controls for any concerned members (post anonymous prayer requests, remove self from map, etc.).

Thoughts?  Concerns?  I'm new to this project, so I'm open to feedback, redirection, etc.  Thanks!

**Comment by seven1m** [comment]
This is a broad desire, but not so much a bug report or feature request. I'd encourage anyone interested in this to create a wiki page and link from the [Roadmap](https://github.com/churchio/onebody/wiki/Roadmap), where this stuff can be fleshed out. Thanks!
