### ISSUE TITLE
404 not found error for assets with nginx

### ISSUE THREAD

**Issue by dreamingblackcat** [churchio/onebody#375]
Hi, I am deploying onebody manually on a VPS. I used nginx and unicorn instead of apache2 and passenger.
Here is my nginx config: /etc/nginx/sites-enabled/onebody.conf
upstream app {
    # Path to Unicorn SOCK file, as defined previously
    server unix:/tmp/unicorn.sock fail_timeout=0;
    server localhost:8080 fail_timeout=0;
}

server {

    gzip on;
    listen 80;
    server_name MY_SERVER_IP;

    gzip_types text/plain text/css application/x-javascript text/xml application/xml application/xml+rss text/javascript applica$
    # Application root, as defined previously
    root /home/rails/public;

    #try_files $uri/index.html $uri @app;
    try_files $uri $uri/ @app;
    location /assets {
       autoindex on;
    }

    location @app {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_redirect off;
        proxy_pass http://app;
    }
   location ~* \.(js|css|png|jpg|jpeg|gif|ico)$ {
        expires 1y;
        log_not_found off;
    }
  

    location ~ ^/(assets|images|javascripts|stylesheets|swfs|system)/ {
        gzip_static on;
        expires     max;
        add_header  Cache-Control public;
        add_header  Last-Modified "";
        add_header  ETag "";

        break;
    }
    error_page 500 502 503 504 /500.html;
    client_max_body_size 4G;
    keepalive_timeout 10;
}

My unicorn.conf is as follow:

listen "127.0.0.1:8080"
worker_processes 4
user "rails"
working_directory "/home/rails"
pid "/home/unicorn/pids/unicorn.pid"
stderr_path "/home/unicorn/log/unicorn.log"
stdout_path "/home/unicorn/log/unicorn.log"

I have precompiled assets. They are in pubic/assets directory. I gave permission of 755 for them.

Problem is when I go to the site, it shows /setup/new page but assets are returned by 404 Not Found.
Is there something missing in my configuration?

**Comment by seven1m** [comment]
Interesting! I've not used nginx much nor unicorn. I asked in [chat](https://gitter.im/churchio/onebody) if anyone has any experience with it. Sorry I don't know what's wrong!

**Comment by seven1m** [comment]
I don't have an actual solution, but you could try setting the environment variable `SERVE_ASSETS=true` (would you do that in the nginx config I suppose?), which will tell Rails to serve up the assets. See the code where this is read here: https://github.com/churchio/onebody/blob/master/config/environments/production.rb#L84-L87

The better solution would be to get nginx to serve the assets directly from the file system, but having Rails serve them might get you by for now...

**Comment by dreamingblackcat** [comment]
Thanks for the replies. In fact, I've changed the stack to passenger+apache2 and it worked out well.
But since I still do not know the actual solution, I will leave the status of this issue to you.  Thanks.

**Comment by seven1m** [comment]
I'm said I don't have a solution for this. I'm going to close though, since we don't actually have instructions for setting up with nginx, so I'll say that is "unsupported". :smiley_cat:

**Comment by seven1m** [comment]
I think I may have found the problem: https://github.com/churchio/onebody/blob/master/config/environments/production.rb#L82

Just documenting here for the next person who comes along and tries to use nginx.

**Comment by seven1m** [comment]
I created a wiki page here: https://github.com/churchio/onebody/wiki/Serving-with-Nginx-and-Passenger
