### ISSUE TITLE
Site Setting > Privacy setting bug

### ISSUE THREAD

**Issue by davidhan527** [churchio/onebody#378]
**Steps to reproduce bug**

![image](https://cloud.githubusercontent.com/assets/4370987/5807004/b1ac0ebc-9fec-11e4-8868-22c201c907dd.png)

1. In the `site settings > privacy` page when I uncheck the option **If enabled, new users will have their home address shared with other site members.** (and I believe this is true for the other privacy options)
1. Create a new user and log in as new user
1. Go to `Edit Profile` and add an address

BUG - Address still shows up in the directory

Also, after unchecking the option **If enabled, new users will have their home address shared with other site members.** and, in the newly created users privacy setting, I believe the address field should be unchecked but it is checked as shown in screenshot below

![image](https://cloud.githubusercontent.com/assets/4370987/5806987/7cc71296-9fec-11e4-89dd-add7bd5216ed.png)

**Comment by seven1m** [comment]
@davidhan527 this seems to be working as designed. I have just pushed code in #451 that should help to clarify why you are still seeing the "hidden" address data (because you are an admin).
