### ISSUE TITLE
Giving: Phase I

### ISSUE THREAD

**Issue by juddey** [churchio/onebody#379]
I'm logging this issue to formalise the work I've been doing on Giving. I've written up a wiki page outlining general functionality of this feature:  https://github.com/churchio/onebody/wiki/Roadmap:-Giving 

I've started work on the admin screens, which are largely done, now I'm up to the admin donations entry screen. I'm using that as an opportunity to learn a bit of js to go with my nice rails.

ETA: No idea. Depends on how long it takes me to learn and do the js portion.

**Comment by seven1m** [comment]
@juddey do you think we should close this? I don't have any personal interest in working on it at this time.

**Comment by juddey** [comment]
No problem, @seven1m. tbh I don't know when I'll be able to get back to looking at this, and the code that I have done is so far past the current version its probably not much use anyway.

**Comment by seven1m** [comment]
We miss you :disappointed:

**Comment by juddey** [comment]
To quote some famous words: "I'll be back" :smiley:
