### ISSUE TITLE
Ruby, JS, and CSS Linter

### ISSUE THREAD

**Issue by buob** [churchio/onebody#396]
Keep our code base in our style guide without having to nitpick or be the bad/annoying guy that constantly comments on it.

**Comment by seven1m** [comment]
:+1:

**Comment by seven1m** [comment]
We were using @houndci for commenting on PRs, but man is it noisy. @x-light how'd you feel about turning that on again? :wink:

**Comment by seven1m** [comment]
FYI @churchio/committers @churchio/contributors, I just reenabled [Hound](https://houndci.com/). Your next PR will likely get some annoying comments unless you check your work with [Rubocop](http://batsov.com/rubocop/) first.

@buob do you know of a way to lint JS and CSS with Travis CI?

**Comment by x-light** [comment]
I :heart: houndci. Really.

**Comment by seven1m** [comment]
Great timing!

![image](https://cloud.githubusercontent.com/assets/669/5945308/516c2b16-a6e2-11e4-94d6-e8e6069e1ab8.jpg)

**Comment by x-light** [comment]
haha - well, better prep your mailservers, I'll start writing CSS soon. ;)

**Comment by seven1m** [comment]
https://linthub.io

**Comment by x-light** [comment]
:+1:

**Comment by seven1m** [comment]
Done in 27561f74801ffc67e8fac83d41f78bddbf132457.
