### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by seven1m** [churchio/onebody#426]
[![Bountysource](https://www.bountysource.com/badge/issue?issue_id=8383722)](https://www.bountysource.com/issues/8383722-german-translation?utm_source=8383722&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by metaxy** [comment]
Could you merge the translations from OneSky?

**Comment by seven1m** [comment]
Yep, done. (Sorry took so long.)

**Comment by seven1m** [comment]
Heads up I uploaded new strings to OneSky. OneBody 3.5.0 should be out in a week or so with improved Import functionality, Facebook login, and more.

**Comment by seven1m** [comment]
@metaxy can I assign you to this ticket?

**Comment by metaxy** [comment]
yes

Am Montag, 7. September 2015 schrieb Tim Morgan :

> @metaxy <https://github.com/metaxy> can I assign you to this ticket?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/churchio/onebody/issues/426#issuecomment-138138106>.
>


-- 
Die Gnade sei mit all denen, die unseren Herrn Jesu Christus lieben in
Unvergänglichkeit! (*Epheser 6:24*)

**Comment by seven1m** [comment]
I just posted a 15 USD bounty for this. It's not much, but @pgeorgi or @metaxy I'll award both of you if you guys can get this to 99%. :smile: :moneybag: 

https://www.bountysource.com/badge/issue?issue_id=8383722

**Comment by seven1m** [comment]
I'm closing all the translation issues to get our bug list down to something workable. Closing this issue does **not** mean we are not continuing to work on (or encourage work on) translations of OneBody -- it only means that we won't track that progress in an issue (OneSky has a better system for tracking progress). Thanks!
