### ISSUE TITLE
Option for including talks or sermons.

### ISSUE THREAD

**Issue by notdodgy** [churchio/onebody#437]
There are two ways this could be done.

The need is to link to a MP3 file in a way that lets a browser play or download it.
Also a link to an optional notes PDF file containing notes/slide.

Files could either be uploaded to the onebody site (as you would a photo / document library) or a link to files hosted elsewhere (e.g. on a file sharing site or Onedrive or Google Drive).
Alongside this it would be also useful to be able to either upload or link to a PDF file for notes/slides

There should be information stored to enable users to search talks.
Date of talk, Type of meeting user defined drop down list) , Title , Speaker (User defined drop down list), Keywords, Link to MP3 file, Link to PDF file.

Options to create a talk / edit a talk  / delete a talk.
Page or "panel" to display 5 or 10 most recent talks
Page where users can list / filter talks.
Having clicked on a talk entry a page or panel where a user can play or download the talk and open / download the PDF file.
Creation of a podcast file, for itunes / podcast users would be useful but not essential.

This is a fairly standard option found on other content management systems, so there should be code / css that can be copied and adapted.  Some have options to include a photo of the speaker.
(HTML5 format tags should tell a browser to play the file defined in the URL - http://www.w3schools.com/html/html5_audio.asp).

Found this tutorial for Ruby on Rails - a lot refers to using Amazon S3 storage, but  it may give some clues.  http://code.tutsplus.com/articles/create-a-simple-music-streaming-app-with-ruby-on-rails--net-18437

**Comment by seven1m** [comment]
@notdodgy I have to be honest, this feels out of the scope of what OneBody is made for. I think maybe your visitor-facing website would be a better place to link to sermons?

**Comment by hunternet93** [comment]
Wordpress does this very well, you could even have OneBody import your church's Wordpress RSS feed. I'm playing with that now, it seems to work great.

**Comment by seven1m** [comment]
I'm going to close this as I don't want to personally commit to making this happen. If someone has experience in this area and wishes to make OneBody handle sermons and audio files, then please let me know!
