### ISSUE TITLE
Don't hide new members from the home screen.

### ISSUE THREAD

**Issue by justinmartin** [churchio/onebody#440]
The first few members populated the home screen, showing the messing "Justin Martin was added to the community".

I can not get new members to show up on that screen.  I can't find any documentation that describes how to get members to show there.

**Comment by seven1m** [comment]
Maybe the user isn't visible?

![screen_shot_2015-02-27_at_7_32_45_pm](https://cloud.githubusercontent.com/assets/669/6424115/8bca07be-beb7-11e4-8698-b77c9dfc9802.png)

**Comment by justinmartin** [comment]
All users have all visibility options checked at this point.

**Comment by seven1m** [comment]
Oh! There is code to limit the number of consecutive entries in the timeline, in order to keep it from getting to reptitive.

If that's confusing behavior, perhaps we could make that configurable. Thoughts?

**Comment by justinmartin** [comment]
I have been adding a members every few days, but I still haven't been able to get any to show.

**Comment by seven1m** [comment]
It's based on what sort of "stream" item came before. Here is the code:

https://github.com/churchio/onebody/blob/master/app/models/concerns/person/streamable.rb#L27-34

Aounds like it's behaving "as designed." Though the design is confusing and should probably be changed. :smiley_cat:

**Comment by seven1m** [comment]
I labeled this as a bug. Shouldn't be too hard to change this behavior in the code.

**Comment by buob** [comment]
Perhaps another way to keep it from getting too repetitive is to have the design similar to facebook's, like "Justin Martin and [13 other people](voip) were added to the community", with a hover state with the other people?

**Comment by seven1m** [comment]
:+1:

**Comment by justinmartin** [comment]
@buob, that sounds like a great idea.

Thanks for the follow up. My church leadership is very excited about implementing OneBody.

**Comment by khebbie** [comment]
Hello!

 

You have a new message, please read <http://eduenter.vn/gathering.php?bw>

 

klaus@hebsgaard.dk
