### ISSUE TITLE
A walk-through UI for new users

### ISSUE THREAD

**Issue by cessien** [churchio/onebody#456]
What: A turbotax-like interface where a first time user is walked through strategic basic questions to set up their profile, connect them to family members and groups they belong in at the church.

The intent of this is to:
1) Make it (even easier) for the non-technical members of a church to set up their profile correctly
2) Create a kiosk style interface to allow people to sign up at a computer in the church very quickly (For my church I would love 10 or so computers temporarily set up in this mode with the technically capable on stand by - church genius bar!)

Example questions:

- "What is your name?" 
- "Do you have family here?"
- "Where do you live?"
- "Upload a profile picture"

An interface like this would be a great way to guide a user through, as well as make small statements about their privacy being respected and how the information will be used!

**Comment by cessien** [comment]
Mockups to come shortly!

**Comment by seven1m** [comment]
Exciting!

**Comment by cessien** [comment]
I'm still working on the mockup screens, but here's the meat of the guided sign up:
https://docs.google.com/document/d/1sR2CeEQBGafnPja3n7ZxgGRXuUqBF3lk4H8glGgfYk0/edit?usp=sharing

**Basic Information** - **Contact Information** - **Family & Relationships** - **Groups & Communities** - **Social Profile** - **Privacy** - **Finished!**

*Each number represents a different screen in the flow, and each bullet represents a section on a page*
<h2>Basic Information</h2>
1. What's your name?
    * (first name, last name, suffix)

2. Tell us more about you.
    * Whats a one or two word description about you? (description)
    * When were you born? (age, gender)
    * Are you married? Congrats! (When’s your anniversary?) (anniversary date)
    * Do you have any allergies? Dietary restrictions, or medical notes (medical notes)

<h2>Contact Information</h2>
1. How may we best contact you?
    * What’s your email address? (primary email)
    * What’s your phone number? with option to add more numbers (phone numbers)
    * Where do you live? (address lines, city, state, zip, country)

<h2>Family & Relationships</h2>
1. Do you have family here?
    * Find or create a family (special logic here for suggesting a created family here, and migrating if so)

<h2>Groups & Communities</h2>
1. Let's join some groups!
    * No creation of groups here, but you can look at and (request if needed to) join groups

<h2>Social Profile</h2>
1. Would you like to upload a profile picture?
    * **good time to mention that they can log in and change everything later**
    * Upload a profile picture
    * Upload a family picture (if a family record exists)
    * Information here about adding social information later (facebook, twitter, testimony, about)

<h2>Privacy</h2>
1. Privacy Settings
    * Are you any of these roles here? Check all that apply. (roles)
    * Privacy checkboxes
    * Do you want to be visible on a printed directory? (name, address and number will be shown)

<h2>Finished!</h2>
1. Thanks for signing up!
    * {{Blurb about authentication scheme being used and how to verify account}}

**Comment by cessien** [comment]
**My design goals** are to keep this process under five minutes. If a section of part of a section is taking too long then I'll change or remove it.

**Imagine a kiosk mode** in the building that people can use to sign up with this, maybe bypass verification emails when enabled (not sure yet)

**On the backend** side of things I'm looking to commit information as soon as the email address step is filled in and the user continues on, then I plan on creating/ using apis to update records and requesting to join groups. At any point after giving an email I want the user to be able to simply exit / skip/ fill out whatever they'd like with this guided wizard.

**Comment by cessien** [comment]
![guided sign up mockup 1](https://cloud.githubusercontent.com/assets/836325/6719405/b4ee3f74-cd90-11e4-87e4-e8fc49139540.png)

**Comment by seven1m** [comment]
:+1:

**Comment by seven1m** [comment]
This looks really cool. Love the progress bar at the top. Exciting!!!!!!!

**Comment by seven1m** [comment]
@cessien I'm going to close this issue to get our list of issues down to a manageable number. If you are still working on it, that is fine -- you can go ahead and make a pull request whenever you are ready to merge.
