### ISSUE TITLE
Custom Tags for pages

### ISSUE THREAD

**Issue by notdodgy** [churchio/onebody#462]
This is suggestion that allows for html tags to be added by using a code in the text.

Here is an example of the sort of thing I am thinking of.
http://manual.openlp.org/display_tags.html 

There would need to be a page / form where tags are defined.

Why do this?

One example of the tag in OpenLP is to embed content such as a web page - a calender or media file/link.

E.g. create a formatting tag called 'web' - with the following code as the front part:
 (left chevron)iframe src="
and this at the end part:
" height="100%" width="100%" (right chevron)This content cannot be displayed (left chevron)/iframe(right chevron)    
(Note that the 'src' part is split over the two tags!).

Then in the content write {web}http://mywebsite.com{/web}, then when you load that page, the webpage will load up.

I have installed using vagrant - where do I find the files where pages are rendered - where I could try coding in some tags?

**Comment by seven1m** [comment]
@notdodgy I'm afraid I don't understand what you're trying to accomplish with these tags. Where would you be able to write these tags and what would they do?

As for Vagrant, wherever you `git clone`'d the code is where the templates are located.

**Comment by notdodgy** [comment]
Web page editors block insertion of HTML apart from simple hyperlinks.
The idea here is that you could include some defined HTML code specified against tags by an administrator. 
The person editing the page only defines the location of the content, not how it is handled.

e.g. it could be used to embed a google calender or a youtube video or an audio file stored on google docs or dropbox. 

An example for audio:

The user would enter {audio}horse.mp3{/audio} but the tags would be substituted with the text to complete the HTML needed to play the file:

```
<audio controls>
  <source src="horse.mp3" type="audio/mpeg">
Your browser does not support the audio element.
</audio>
```

**Comment by seven1m** [comment]
@notdodgy I'm sorry I still don't understand **where** these tags would be used? OneBody isn't really a general blog or content management system -- it doesn't seem to me like we need custom tags.

Given that this seems like a feature more for a developer and less for a regular user, I cannot imagine us implementing something like this. I'd prefer we do more intelligent handling of attachments and other file uploads, e.g. embedded previews for doc and pdf files would be awesome.
