### ISSUE TITLE
Allow groups to have more than one leader

### ISSUE THREAD

**Issue by aunderwo** [churchio/onebody#463]
Change 1-1 relationship between group and leaders into to  group has_many leaders

**Comment by acbilimoria** [comment]
I'm just getting started on this

**Comment by seven1m** [comment]
@acbilimoria great! Hop in [chat](http://chat.church.io) if you want to discuss.

**Comment by acbilimoria** [comment]
Cool, thanks!  Here's what I have so far.. am I on the right track with this?  https://github.com/acbilimoria/onebody/commit/0c276b244673cb259adfbdd3bc9dd176b79d684b
https://github.com/acbilimoria/onebody/commit/ac0f7609820dac7f4a553cbe479104f6af540432

**Comment by seven1m** [comment]
@acbilimoria looks like a good start! I made a comment on one of the commits.

Also, I think you can go ahead and get rid of the existing `leader` column. Just be sure to include code in your migration to save the existing leader as a GroupLeader. Let me know if you need help with that part!

**Comment by acbilimoria** [comment]
Cool, so if we migrate the Group.leader_id to the many to many table, instead of  .leader_id || .leaders, I can just use .leaders?

**Comment by seven1m** [comment]
Yep!

**Comment by acbilimoria** [comment]
@seven1m I'm stumped trying to get the option tag to have a value that accepts_nested_attributes_for can use.  Each group_leader should have the following params: id (if applicable), _destroy (if applicable), group_id, person_id.

It could hypothetically be handled in models/group.rb, which was my first approach, but I'm stumped there too:  https://github.com/acbilimoria/onebody/tree/leaders

Any chance you could take a look?

**Comment by seven1m** [comment]
Yep, I'll try to take a look in the next few days. Thanks!

**Comment by acbilimoria** [comment]
Happy Holidays!  This might be something to keep an eye on as we're working through it:    https://github.com/rails/rails/issues/22358

**Comment by seven1m** [comment]
I ended up taking a slightly different approach to this by setting a boolean `leader` column on the membership record.
