### ISSUE TITLE
Unable to upgrade to 3.4.0

### ISSUE THREAD

**Issue by justinmartin** [churchio/onebody#469]
My installation is running on DigitalOcean and was installed with the installer script.  The last update installed just fine.

When I checkout 3.4.0 and run bundle install, I get the following message:

```
You are trying to install in deployment mode after changing
your Gemfile. Run `bundle install` elsewhere and add the
updated Gemfile.lock to version control.
```

I'm not sure how to move forward.

Thanks.

**Comment by cessien** [comment]
Did you try running:
rm -rf /var/www/onebody/vendor/bundle

and then bundle install? There might be a bug in the script because of the change, but I don't use digital ocean

https://github.com/churchio/onebody/wiki/Manual-Installation#version-specific-upgrade-information

**Comment by justinmartin** [comment]
I did remove the the vendor/bundle folder.

I followed the instructions at the link provided. I'm not sure what I did.

**Comment by cessien** [comment]
Hey @justinmartin, I was able to reproduce your issue. To get it working I had to do `bundle install --no-deployment` then `bundle update` then `bundle install`. The no deployment flag should allow you to get the right gems and the other commands will put you on the right track for the future. 
I'm not sure at what level of a bug this should be classified @seven1m or if there's  way to handle this?

**Comment by seven1m** [comment]
That's odd -- not sure why that's needed.

Oh well. I updated the wiki.

**Comment by justinmartin** [comment]
Awesome.  Thanks so much.

**Comment by seven1m** [comment]
Thanks @cessien for tracking this down!!
