### ISSUE TITLE
Let Tasks be assigned to groups

### ISSUE THREAD

**Issue by hunternet93** [churchio/onebody#471]
My church's current church management software allows groups to have Projects that track any volunteer work, crafts, etc. that each group is doing. I think OneBody's Tasks could be used similarly, a task could be assigned to a group instead of a single person.

**Comment by seven1m** [comment]
:+1:

**Comment by AndyGauge** [comment]
I'm at about [40% ](https://github.com/AndyGauge/onebody/tree/feature/tasks_as_a_group).
Adds "All Members" to Assigned To drop down for Tasks.
