### ISSUE TITLE
Contributing: GPA and Test Coverage!

### ISSUE THREAD

**Issue by brunoocasali** [churchio/onebody#475]
I work in a company that cares about the code that develops.

I'm not here to advertise where I work, but ask you, if you do it in this project, because I wanted to contribute my experience and availability like you. Since refactor code that stinks to improve the speed of specs.

I am writing this before doing something, because there are many projects using cool tools like CodeClimate, but do not use it really, don't trying to improve the code as it suggests. So I can help the project with some tips and code refactorings, and style as well, based on Ruby Style Guide.

What do you think?

**Comment by seven1m** [comment]
@brunoocasali I'm all for improving test coverage and cleaning up code. I made some major progress toward improving our CodeClimate score earlier in the year and intend to keep doing that as the year carries on and I get inspired. While not our primary goal, I recognize that cleaning up the dusty corners of the app will help other contributors and reduce bugs.

I welcome you to contribute any way you can. You can start by making a small clean-up and posting a Pull Request. Recognizing our code styles / methods for refactoring may differ significantly, I'd like to start small.

Thanks!

(Closing this issue -- post your PR and we'll review!)
