### ISSUE TITLE
Datepicker doesn't fill the year in date fields

### ISSUE THREAD

**Issue by gustavobim** [churchio/onebody#488]
When I select a date using the date picker (New Person, Edit Person, Attendance) it only fills the day and month, ignoring the year.

Example: If I choose a January 14th, the field is filled with: "14/01/".
I tried to change the date format to the original one and the issue happens as well.

**Comment by seven1m** [comment]
@gustavobim this works fine for me, using both `%m/%d/%Y` and `%d/%m/%Y` date formats.

1. What browser are you using?
2. Are you able to reproduce in other browsers?
3. What is your org's date format?

**Comment by seven1m** [comment]
Closing. @gustavobim reopen if you continue to see this bug on the lastest `master` branch.
