### ISSUE TITLE
Afrikaans translation

### ISSUE THREAD

**Issue by attieretief** [churchio/onebody#489]
Hi there

I would like to translate onebody to Afrikaans

Where to I start?

**Comment by benjaminsigidi** [comment]
@attieretief boet i believe you need you will have to do a pull request for that.  Create a folder called af-ZA in the https://github.com/churchio/onebody/tree/master/config/locales  then copy all the files from english https://github.com/churchio/onebody/tree/master/config/locales/en then afrikaans away :)

**Comment by attieretief** [comment]
Nah, I'm pretty sure tim wants to manage it through OneSky

**Comment by x-light** [comment]
We manage translations through onesky so that multiple people can have access without having to use version control (at least that's my understanding). If you were *super* keen you could always start on the ZA yml files directly :)

anyway @seven1m will be here soon and he'll be able to direct traffic.

**Comment by attieretief** [comment]
I'll wait for @seven1m

**Comment by attieretief** [comment]
@seven1m go ahead and assign this to me, and set the in progress label - I'm well under way ;)

**Comment by seven1m** [comment]
Heads up I uploaded new strings to OneSky. OneBody 3.5.0 should be out in a week or so with improved Import functionality, Facebook login, and more.

**Comment by seven1m** [comment]
I'm closing all the translation issues to get our bug list down to something workable. Closing this issue does **not** mean we are not continuing to work on (or encourage work on) translations of OneBody -- it only means that we won't track that progress in an issue (OneSky has a better system for tracking progress). Thanks!
