### ISSUE TITLE
Manage Group Administrators Issue

### ISSUE THREAD

**Issue by hooray4me** [churchio/onebody#490]
When I click the "Mange Group Administrators" link in the Manage Admins dashboard, nothing renders on the page. I'm thinking maybe a permissions issue? No sure. Any Ideas?
![image](https://cloud.githubusercontent.com/assets/12399138/7891664/1438f7d8-0614-11e5-99df-0dcbb7d5dbba.png)
![image](https://cloud.githubusercontent.com/assets/12399138/7891702/67ca401e-0614-11e5-88e8-ef9158080c8e.png)

**Comment by x-light** [comment]
@hooray4me - welcome!

Here are some questions to start:
* Have you set up groups?
* Is there anyone in them?
* Does the group have a leader? (Leaders are automatically admins, from memory)

(Sorry if this seems condescending, just trying to start at the beginning :)

**Comment by hooray4me** [comment]
I've created about 40 groups. I added myself as a leader for one of them.

**Comment by hooray4me** [comment]
To elaborate, when I click on the link it seems like the page "wants" to render something, like it "blinks" then stays blank.

**Comment by x-light** [comment]
Oh dear :disappointed: 
I'm running up an install of OB today and I'll check this out to see if I can figure out what the issue is. I'll come back to you.

**Comment by cessien** [comment]
Just pointing it out, I'm not sure but it may be this issue here:
https://github.com/churchio/onebody/issues/476

**Comment by hooray4me** [comment]
I did have that problem to and couldn't access the admin section as well, but I was able to fix it by doing the chmod's etc...

**Comment by x-light** [comment]
Just letting you know that I've attempted install with vagrant today but no dice. Will attempt a full local install tomorrow.

**Comment by hooray4me** [comment]
Any updates on this? Its one of the only things holdings me up

**Comment by x-light** [comment]
I hope to do some more today. See #493 for more details.

**Comment by hooray4me** [comment]
Just so you know I did a manual install and not with vagrant

**Comment by x-light** [comment]
Did it complete successfully? I've got a problem with bundler which I'm hoping to look at today.

**Comment by hooray4me** [comment]
For the most part it did... had to sudo bundle install otherwise I couldn't get past it...

**Comment by x-light** [comment]
hmmm thats odd. Shouldn't have to do that. but anyway, if you have a running dev instance you are further ahead than I am! :)

**Comment by hooray4me** [comment]
it would pass everything during the bundle without sudo EXCEPT gemfile.lock

**Comment by x-light** [comment]
hmm let me see how far I get and I'll come back to you.

**Comment by hooray4me** [comment]
also installed in ubuntu 15.04

**Comment by x-light** [comment]
cool thanks! I've gotta run, but will post an update this afternoon - even if its just to say there's no update :wink:

**Comment by x-light** [comment]
I've managed to get my local dev install going today so have been able to look into this.  

You are right when you say that the page is looking for something. Its looking for all people who are currently set as administrators of the group, excluding yourself. (You can't edit yourself - from memory this was a security feature).

If you haven't got anyone in the group then you can't mark anyone as an administrator and therefore you won't see anyone in the Group Adminstrators page. (which came first, the chicken or the egg...? ;)

To make someone an administrator, head to the group launch page, and click on the members link:

![selection_022](https://cloud.githubusercontent.com/assets/7445602/7909298/58245ad6-089f-11e5-9a2f-f4e775cc52ad.png)

You'll get something like this:

![selection_023](https://cloud.githubusercontent.com/assets/7445602/7909337/87fb1696-089f-11e5-896f-266434eacbba.png)

You can use the promote and demote buttons next to each person to make the person a group administrator.

After doing this, if you go back to the Group Administrators page, you should get something back:
![selection_024](https://cloud.githubusercontent.com/assets/7445602/7909386/ead6fc9e-089f-11e5-8cfe-aa55949ca32c.png)

If you follow the link it will take you back to the groups memberships page. HTH, let us know if you have further questions :)

**Comment by hooray4me** [comment]
Thanks! This is what I needed!

**Comment by seven1m** [comment]
Wow that Group Admins page is ugly. I'm thinking it never got any <3 before we released 3.0. I'll work on updating it.
