### ISSUE TITLE
Email Issues

### ISSUE THREAD

**Issue by hooray4me** [churchio/onebody#491]
I have 2 issues. First Issue my postfix emails are flagged as spam by default. I have the proper spf/mx records in place and the headers reflect that it passes. The issue is that the email is "Received: from example.com" during the relay. I have tried everything and cannot figure out where it's picking up "example.com"... See below(red)
Second issue: I have added SSL to the site and done a permanent http to https redirect in the virtual site. How do I get the emails that get sent to reflect the https address. See below(blue)

![image](https://cloud.githubusercontent.com/assets/12399138/7893762/8fc23448-0626-11e5-9b99-61a1acbe62ed.png)

**Comment by hooray4me** [comment]
I figured out how to correct the Received: from example.com problem by adding header_checks
/Received: from example.com*/   IGNORE

**Comment by seven1m** [comment]
@hooray4me did you edit the enail.yml config file so it says your domain? https://github.com/churchio/onebody/blob/master/config/email.yml.example

**Comment by hooray4me** [comment]
son of a bee sting... I had edited it during my installation but left the domain as example.com... Thanks a lot! Any idea on the getting the links in the email to show https?

**Comment by seven1m** [comment]
The links are wrong due to a bug. That needs to be corrected in the code. I opened #497 for that.
