### ISSUE TITLE
Bulk Import users + group membership

### ISSUE THREAD

**Issue by hooray4me** [churchio/onebody#492]
I need a way to do a bulk import of around 700 users with group membership preferences. We recently did a stewardship campaign and have all of the choices of each parishioner's 44+ group membership options dumped into an excel spreadsheet. How can we take a big bang approach to this?

**Comment by seven1m** [comment]
Import the people usingn CSV import. The group info should go in a column labeled "classes", comma-separated.

You can then create one or more groups and "link" the groups to these class codes.

There is a bit of info about making "linked" groups here: https://github.com/churchio/onebody/wiki/How-Group-Membership-Works

**Comment by hooray4me** [comment]
So to clarify, I would do the following:
Export my list of 44 existing groups, add a number to the link_code for the each group and re-upload, then, when I upload all my users I would add each users memberships in the classes header 20,22,etc... correct? One question (If I have this right) if this is a csv, does it affect the import delimiting each class with a comma?

**Comment by seven1m** [comment]
That sounds it should work as you stated, though usually this feature is used for syncing with an external system with its own group ids.

If you're using Excel to build the CSV file it will automatically surround the field with double quotes so the commas don't interfere with other fields.

**Comment by hooray4me** [comment]
thanks, if you can figure out the solution to my problems in Issue #490 then all my problems will be solved!
