### ISSUE TITLE
No feedback for domain validation

### ISSUE THREAD

**Issue by tallpauley** [churchio/onebody#495]
Grabbed virtual appliance, setup port forwarding and run:
https://church.io/downloads/onebody/virtual-appliance/onebody-3.4.0-1.zip

At http://localhost:8080/setup, I entered no domain name. Instead of giving me feedback that I should enter a domain name when I clicked "save changes", all the form fields were simply erased.

**Comment by toreyheinz** [comment]
I'm willing to work on this. I've looked into a bit and can see where current the logic is held.

I have question about where/how you would like me to spec this out? I can see a need/place to create a models/setup_spec.rb, but I didn't see any feature/integration tests. I do see a number of controller specs, but  I normally don't spec those out too much.

So I guess the question is are you OK with me setting up a features folder for the setup integration spec?

OH, I see some request specs, but I could put it there if you like.

Torey

**Comment by seven1m** [comment]
@toreyheinz we'd love for you to help out on this!

You're right that we don't use integration tests to much effect -- they tend to be slow and a bit overkill for our needs. A simple controller test should suffice for this I think.

That being said, we'll certainly take any contribution you can make, no matter how (if) it's tested! 😀

Please let me know if you need any help!!

**Comment by toreyheinz** [comment]
@seven1m I setup a unit test, and verified through screenshot ;)
I found another bug... I think, it seems that the settings are not getting updated, but I may doing something wrong I left that pending.

I can issue a pull request, and we can discuss there, or I can make some a couple more changes first.

<img width="727" alt="screenshot 2015-07-27 15 03 27" src="https://cloud.githubusercontent.com/assets/23319/8915816/43cc15e0-3475-11e5-8f76-3c94b2d30ebb.png">

**Comment by seven1m** [comment]
Pull request!!!

**Comment by toreyheinz** [comment]
Looks like there is an order dependent test failure `rspec --seed 20417`. I'll look to see if it was caused by spec.
