### ISSUE TITLE
Changing user email throws error.

### ISSUE THREAD

**Issue by hooray4me** [churchio/onebody#502]
I am trying to correct an email address for one of my users... I changed one mis-typed letter and then try to save and it throws an error. Any Ideas?

![image](https://cloud.githubusercontent.com/assets/12399138/7984752/f078f02e-0a90-11e5-97cc-41c47ac878ae.png)
![image](https://cloud.githubusercontent.com/assets/12399138/7984758/f99a3f1e-0a90-11e5-94ba-2ab4bbb5b4e2.png)

**Comment by seven1m** [comment]
Check the `log/production.log` for errors. My guess is your email server isn't set up fully.

**Comment by seven1m** [comment]
(This would happen because when an email is changed, a notification enail is sent to the admin. If your mail server isn't set uo, then an error would occur.)

**Comment by hooray4me** [comment]
Thanks, I migrated this virtual server and postfix didn't want to start... one the lines in the master.cf got mad cause it didn't have a space in front if it. After editing I was able to successfully start postfix and the error cleared up
