### ISSUE TITLE
Username OR email Address option?

### ISSUE THREAD

**Issue by hooray4me** [churchio/onebody#508]
I have MANY parishioners who share one email address... Is there a way to allow the 2nd member of the family to have a username instead of only an email address?

**Comment by Tr4pSt3R** [comment]
One option will be to use this system. Suppose your email is john.doe@example.com. Everyone else within the family can use john.doe+1@example.com, john.doe+2@example.com etc.

**Comment by seven1m** [comment]
People in the same family can share an email address for logging in as long as their passwords differ.

**Comment by Tr4pSt3R** [comment]
Ah there you go @hooray4me that is a much smarter solution with no mess

**Comment by hooray4me** [comment]
So If I set the email address the same for both family members, then send a password setup email from each profile, will they be able to differentiate between the 2 setup emails?

**Comment by Tr4pSt3R** [comment]
That's a very good question @hooray4me that will need to be tested.

**Comment by seven1m** [comment]
@hooray4me I had to refresh my memory, but we do allow the user to select which user they are when setting their password. The link they get in their email sends them to a page that looks like this:

<img width="590" alt="screen shot 2015-07-16 at 12 02 21 pm" src="https://cloud.githubusercontent.com/assets/669/8729750/9e1928ba-2bb2-11e5-9a6b-2ac05a50de04.png">

After that selection, they can set the password for their account.

Does this work for your purposes?

**Comment by hooray4me** [comment]
Yes it does thanks!
