### ISSUE TITLE
Video Support

### ISSUE THREAD

**Issue by hooray4me** [churchio/onebody#510]
Would it be possible to add the ability to support uploading/linking of videos?

**Comment by seven1m** [comment]
Not sure... Would need to investigate!

**Comment by Tr4pSt3R** [comment]
First of all, is it currently possible to add videos? 
@hooray4me what do you mean by "linking of videos". Are you requesting for the ability to tag people to videos, add embeddable links for the videos, etc?

**Comment by seven1m** [comment]
OneBody does not currently support video uploads.

**Comment by hooray4me** [comment]
I guess this would be more of a feature request?

**Comment by seven1m** [comment]
Yep!

**Comment by seven1m** [comment]
Some things to investigate:

1. how to encode videos
2. where to store videos (self-hosted or third-party service)

If anyone has interest and/or expertise in this area, please chime in!!!

**Comment by hunternet93** [comment]
I have zero Ruby experience, but I'd be happy to help as I can. I have a bit of web video experience thanks to Cedar's media handling, I used FFMpeg with a node.js wrapper, and just threw the videos is a user-specified directory. Most browsers handle mp4-encapsulated H.264/AAC and also WebM, you could use ffprobe to determine if the video's a supported format and re-encode it if not. The HTML5 <video> tag would be the easiest way to embed videos, although if you want to support older browsers as well then there are JS libs that will automatically switch between HTML5 and Flash video.

**Comment by Tr4pSt3R** [comment]
I think the real challenge will be building a video platform. a Video content deliver network

**Comment by hunternet93** [comment]
A CDN might be a bit out of OneBody's scope :smile:. Serving up videos from a single server via HTTP works just fine in my experience, as long as we're not talking YouTube-levels of traffic. 

One other thing, videos in MP4/MOV containers often need to be rearranged to the video index is at the front of the file, and not the back, so videos don't have to fully download before playing. FFMpeg includes a tool called `qt-faststart` that does this, or you can just use plain ffmpeg: `ffmpeg -i video.mp4 -movflags faststart video-faststart.mp4`

**Comment by seven1m** [comment]
@hunternet93 thank you for your help!!

**Comment by seven1m** [comment]
I'm going to close this as I don't want to personally commit to making this happen. If someone has experience in this area and wishes to make OneBody handle video, then please let me know!
