### ISSUE TITLE
Attachments for group message

### ISSUE THREAD

**Issue by hooray4me** [churchio/onebody#513]
It was brought to my attention that attachments are not working for group messages. How should I go about troubleshooting this?
![image](https://cloud.githubusercontent.com/assets/12399138/8767107/27c6ff7c-2e17-11e5-8c21-d9261d45155f.png)
![image](https://cloud.githubusercontent.com/assets/12399138/8767109/2fd63b60-2e17-11e5-9706-a4f60a264bdd.png)

**Comment by seven1m** [comment]
Check the permissions on your `public` folder. You need to give the web user (usually `www-data`) write access there.

**Comment by hooray4me** [comment]
I did the following:
sudo chgrp -R www-data public
sudo chmod -R 770 public

Now when I attach a file to a group message and send it the page shows blank...
![image](https://cloud.githubusercontent.com/assets/12399138/8768916/b63691f8-2e55-11e5-883e-66114a6658e1.png)

**Comment by hooray4me** [comment]
Is there a log I should review to try and track down the issue?

**Comment by seven1m** [comment]
@hooray4me I'm not sure what would cause a blank screen like that. I would check the `log/production.log` to see if there is any clue as to what is happening.

**Comment by hooray4me** [comment]
Its back to saying were sorry but something went wrong. Any other ideas?

**Comment by cessien** [comment]
Did you check that log? Are any errors spitting out?could you try creating a group with one person (you) and send an attachment? I'm shooting in the dark for what's failing

**Comment by hooray4me** [comment]
I didn’t see anything glaring in that log. I have tried several different groups in addition to a group where I am the only member. I also changed from postfix to mailgun to rule out a config issue with mail.

**Comment by hunternet93** [comment]
Try checking Apache's error logs (`/var/log/apache2/error.log` on Debian), I remember having a similar issue in the past and finding the answer there. (I sadly don't remember what the problem _was_, though...)

**Comment by hooray4me** [comment]
Thanks, that led me to it! Did a chmod 777 on files and wala!

App 12758 stderr: Command :: file -b --mime '/tmp/bf57c906fa7d2bb66d07372e41585d9620150722-12773-9wdvw4.xlsx'
App 12758 stderr: Completed 500 Internal Server Error in 121ms (ActiveRecord: 11.0ms)
App 12758 stderr:
App 12758 stderr: Errno::EACCES (Permission denied @ dir_s_mkdir - /var/www/onebody/public/system/production/attachments/files/3):
