### ISSUE TITLE
Mapquest geocoder API always returns Latitude and logitude of US even when I give invalid address in request

### ISSUE THREAD

**Issue by laveenaBachani** [churchio/onebody#515]
http://open.mapquestapi.com/geocoding/v1/batch?key=Fmjtd%7Cluur200y2l%2Cb0%3Do5-9a1l50&outFormat=json&inFormat=json&json={"locations":[{"street":"vfdbgfb","state":"fdbgfbgf","postalCode":"","country":"","city":""}]}

If I give invalid URL,then too its giving latitude and longitude of US.I want Nothing should come if I give invalid parameter.

**Comment by Tr4pSt3R** [comment]
Hi @laveenaBachani I think it's far easier to check the json response to see if it's empty rather than return nothing, as a whole

**Comment by laveenaBachani** [comment]
No Its gives a response.Its does not returns nothing.

**Comment by Tr4pSt3R** [comment]
@laveenaBachani you mean you expect it to explicitly return an error message?

**Comment by laveenaBachani** [comment]
@Tr4pSt3R  Yes.Or It should return no result.

**Comment by Tr4pSt3R** [comment]
Oh okay, I think I understand what you mean. Validation incorrect URLs is always a tricky business as URLs come in many complex shapes and forms. Which part of the url do you want to validate?

The domain name: ```open.mapquestapi.com```?
The data definition: ```batch?key=Fmjtd%7Cluur200y2l%2Cb0%3Do5-9a1l50&outFormat=json&inFormat=json&json={"locations":[{"street":"vfdbgfb","state":"fdbgfbgf","postalCode":"","country":"","city":""}]}```

**Comment by seven1m** [comment]
@laveenaBachani we don't use the Mapquest geocoder any more -- we're using the Google one since 3.4.0. Please upgrade and let us know if that fixes your issue.

**Comment by Tr4pSt3R** [comment]
Thanks for the info @seven1m
