### ISSUE TITLE
Onebody Mail issues

### ISSUE THREAD

**Issue by hooray4me** [churchio/onebody#516]
This is driving me nuts. I'm not an expert in postfix, but i've learned alot. For the life of my I cannot get dkim to sign my outgoing emails so that they don't get caught by spam filters... The headers say dkim=none. I've already setup proper spf. Any insight would be greatly appreciated.

**Email Header:**
x-store-info:sbevkl2QZR7OXo7WID5Zceyr2rpwhT9xD/iv74iR8SOUQH1mcqQIlQtTCVEeSMKUDC4QT+3iiKz7dAbcBewWRD3DDnJLS/h4bhT3zt5jfdUDhDwGbJGMuCsUIRpWPo+ZSsSsSAADq/1EeWGF6NzqtQ==
Authentication-Results: hotmail.com; spf=pass (sender IP is 64.39.X.X; identity alignment result is pass and alignment mode is relaxed) smtp.mailfrom=noreply@onebody.[MYDOMAIN].org; **dkim=none** (identity alignment result is pass and alignment mode is relaxed) header.d=onebody.[MYDOMAIN].org; x-hmca=pass header.id=noreply@onebody.[MYDOMAIN].org
X-SID-PRA: noreply@onebody.[MYDOMAIN].org
X-AUTH-Result: PASS
X-SID-Result: PASS
X-Message-Status: n:n
X-Message-Delivery: Vj0xLjE7dXM9MDtsPTA7YT0xO0Q9MTtHRD0xO1NDTD0w
X-Message-Info: NhFq/7gR1vTnYzO7gVb75/Rv6pdJyqocxcgh7AcZ/s4nE7m8B3M2HtUCQWWakbphpB/KZz35fNudX3ilW1ShMbuwiR24obfg02aHpxOZsBk/QawhGBJgEqcr+zvFa6DvwzM7d20VIArvuTVBioTN5rgAKnbwkpy17nhCOnK0LT07v9ac9mzUE+El0bCRc30lFd7nEHe53SncY2Y+Lzi0VVaLTJrz8V2pHDi0/lWKNkQ=
Received: from mail.onebody.[MYDOMAIN].org ([64.39.X.X]) by BAY004-MC6F13.hotmail.com with Microsoft SMTPSVC(7.5.7601.23008);
	 Tue, 4 Aug 2015 17:48:14 -0700
Received: from onebody.[MYDOMAIN].org (mail.onebody.[MYDOMAIN].org [127.0.0.1])
	by mail.onebody.[MYDOMAIN].org (Postfix) with ESMTP id 7791741698
	for <[personalEmail]@outlook.com>; Tue,  4 Aug 2015 19:48:13 -0500 (CDT)
Date: Tue, 04 Aug 2015 19:48:13 -0500
From: "Rob Hedrick [Computer Skills]" <noreply@onebody.[MYDOMAIN].org>
Reply-To: Rob Hedrick <[personalEmail]@outlook.com>
To: [personalEmail]@outlook.com
Cc: Computer Skills <technology@onebody.[MYDOMAIN].org>
message-id: <61_829685_55c15d4d72813_d62159ecfb4253db@web1.mail
Subject: test6
Mime-Version: 1.0
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: 7bit
List-ID: Computer Skills group on ONEBODY
 <technology.onebody.[MYDOMAIN].org>
List-Help: <http://onebody.[MYDOMAIN].org/groups/44>
List-Unsubscribe: http://onebody.[MYDOMAIN].org/groups/44/memberships/1?code=a659bd1bd70fbc2fb8601c52bdf4f1f6bfe4e6d39f3a967900&email=off
List-Post: <http://onebody.[MYDOMAIN].org/groups/44>
List-Archive: <http://onebody.[MYDOMAIN].org/groups/44>
Return-Path: noreply@onebody.[MYDOMAIN].org
X-OriginalArrivalTime: 05 Aug 2015 00:48:14.0230 (UTC) FILETIME=[690BF360:01D0CF18]

test6
- - - - - - - - - - - - - - - - - - - - - - - -
Hit "Reply" to send a message to Rob.
Hit "Reply to All" to send a message to the group Computer Skills, or send to technology@onebody.[MYDOMAIN].org.
Group page: http://onebody.[MYDOMAIN].org/groups/44
To stop email from this group:
http://onebody.[MYDOMAIN].org/groups/44/memberships/1?code=a659bd1bd70fbc2fb8601c52bdf4f1f6bfe4e6d39f3a967900&email=off
Message ID: 61_829685

**mail.log:**
Aug  4 20:03:01 mail pop3d: Connection, ip=[::1]
Aug  4 20:03:01 mail pop3d: LOGIN, user=onebodymail, ip=[::1], port=[42521]
Aug  4 20:03:01 mail pop3d: LOGOUT, user=onebodymail, ip=[::1], port=[42521], top=0, retr=0, rcvd=12, sent=39, time=0
Aug  4 20:03:01 mail postfix/pickup[31034]: B10FF4169A: uid=0 from=<root>
Aug  4 20:03:01 mail postfix/cleanup[31062]: B10FF4169A: message-id=<20150805010301.B10FF4169A@mail.onebody.[mydomain].org>
**Aug  4 20:03:01 mail opendkim[30874]: B10FF4169A: DKIM-Signature field added (s=mail, d=onebody.[mydomain].org)**
Aug  4 20:03:01 mail postfix/qmgr[31035]: B10FF4169A: from=<root@onebody.[mydomain].org>, size=721, nrcpt=1 (queue active)
Aug  4 20:03:01 mail postfix/local[31064]: B10FF4169A: to=<root@onebody.[mydomain].org>, orig_to=<root>, relay=local, delay=0.07, delays=0.05/0/0/0.01, dsn=2.0.0, status=sent (delivered to maildir)

**Comment by seven1m** [comment]
@hooray4me I'm sorry, that stinks! I really know nothing about dkim -- I never set it up on my postfix server. I don't seem to have a problem with landing in spam folders. Be sure to check that your IP isn't on any blocklists. Here's a tool to check for you: https://mxtoolbox.com/blacklists.aspx

**Comment by seven1m** [comment]
I'm going to close as it's out of the scope of the product. You might look into switching to using Mailgun as they do a good job of getting through spam filters.
