### ISSUE TITLE
Multi-document upload

### ISSUE THREAD

**Issue by cessien** [churchio/onebody#523]
We have someone here uploading a ton of files so that can access them through onebody. What would we want a multi-document uploading system to look like? I imagine a grid system where you can add and upload rows and fill in a file/ description.

Maybe this can turn into a feature request if the idea seems feasible

**Comment by seven1m** [comment]
@cessien this is good idea. I'm thinking a multi-file dialog (select all the files you want to upload to the current folder), then present the user with a list of all files about to be uploaded with name and description fields.

I'm thinking this...

1. User clicks the "Upload multiple" button
2. User selects all the files they want in the regular OS file chooser
3. User is presented with a screen like this one:

![screen shot 2015-09-05 at 10 30 56 am](https://cloud.githubusercontent.com/assets/669/9699969/6f63567e-53b9-11e5-9272-2e81c35f4520.png)

**Comment by cessien** [comment]
Sounds like I imagined too!

**Comment by seven1m** [comment]
@cessien in the most recent updates to Documents, I made the upload form a bit smarter. It now enters the title for you when you select a file. I agree it would still be nice to allow multiple files be uploaded at once, but just thought I'd pass it along in case it makes your life a little easier. :smile:

**Comment by cessien** [comment]
Can we mark this as in progress?

**Comment by seven1m** [comment]
Oh! This was finished in #542!!!
