### ISSUE TITLE
Bug printing directory with PNG images

### ISSUE THREAD

**Issue by yuy0311** [churchio/onebody#528]
![screen shot 2015-09-08 at 11 38 31 am](https://cloud.githubusercontent.com/assets/632941/9724659/710bac30-561e-11e5-9f02-da818aaa55de.png)
Hi All,

Try to print directory with family images, but in the tmp folder. None of the pdf has anything in it. 
Has anyone got the same experiences? How can I fix it?

Regards
Yang

**Comment by cessien** [comment]
I think I remember having an issue where people in the directory that don't have an exposed address don't appear?

It's been a while but try making sure the address for one of your members are visible and generate it again.

**Comment by cessien** [comment]
Also take a peek at logs

**Comment by yuy0311** [comment]
Thanks for the quick reply. I will give a try. I can't see any useful message in the production.log file. 
<img width="618" alt="screen shot 2015-09-08 at 11 59 30 am" src="https://cloud.githubusercontent.com/assets/632941/9724828/1e31ce6a-5621-11e5-98ed-a07c6ee1a139.png">

**Comment by seven1m** [comment]
@yuy0311 are you saying the PDF is completely empty/blank, or that it just doesn't have any people in it. I mean, does it have the title page?

**Comment by yuy0311** [comment]
@seven1m  It's completely empty 0b file size. The issue only happens when I try to print with family photo. Without photo, the file is generated correctly, with the title page.

**Comment by yuy0311** [comment]
@cessien Have updated the address in every family members. No directory pdf was generated with I ticket the photo. Any inside for this?

**Comment by seven1m** [comment]
Sounds like a bug then. I'll take a look soon.

**Comment by yuy0311** [comment]
@seven1m Thanks, please let me know if i can provide some useful information to you to track down this.

**Comment by yuy0311** [comment]
@seven1m Found the issue. It is due to the PNG photo that cause the print directory with image failed. 
Will you support PNG photo in future or JPG only?

**Comment by seven1m** [comment]
Oh wow! I wasn't aware of that. Let's leave this open as a bug ticket and I'll see if I can get that fixed.

Thanks!

**Comment by seven1m** [comment]
@yuy0311 let me know if this fixes it for you!

(This bug fix will be in the next release in a few weeks, or you can check out the latest `master` branch of OneBody and give that a go.)

**Comment by yuy0311** [comment]
@seven1m Yes, will give a try. Thanks
