### ISSUE TITLE
Reporting Dashboard - Group Contact Details Broken

### ISSUE THREAD

**Issue by hooray4me** [churchio/onebody#530]
The Group Contact Details page in the reporting dashboard appears to be broken.
![image](https://cloud.githubusercontent.com/assets/12399138/9766534/0ce8e36e-56df-11e5-9309-f159dd125460.png)

**Comment by juddey** [comment]
@hooray4me are you running postgresql? I found that this report was broken on that db platform. (tsk tsk me writing platform dependent SQL)

**Comment by hooray4me** [comment]
nope.

**Comment by seven1m** [comment]
@juddey I upgraded some gems and didn't notice the view was broken. :grimacing:

**Comment by seven1m** [comment]
@hooray4me let me know if that fixes it for you!

**Comment by hooray4me** [comment]
Yep that fixed it! Thanks!

**Comment by khebbie** [comment]
Hello!

 

You have a new message, please read <http://husband.tv/amount.php?d>

 

klaus@hebsgaard.dk
