### ISSUE TITLE
Arrange service through onebody

### ISSUE THREAD

**Issue by khebbie** [churchio/onebody#536]
As a Minister
I want to arrange a service
So that we can coordinate the people involved in a service

As a minister
I want to share the liturgy
So I can work with the volunteers to arrange the service

As a group leader (ie worship leader or technical group leader)
I want to open requests for volunteers (ie. drummer or the guy who runs the projector during the service) to help
So that people can tell me when they are available to help

As a group leader
I want to assign people to a service
So I know and can communicate about who is helping in a service

As a member of the congregation 
I want to see the service in my calendar
So that I know when it is taking place.

**Comment by seven1m** [comment]
@khebbie my fear in adding this to OneBody is that it would be a fairly large scope increase for a small team. We're already an online directory and social network -- do we want to maintain a volunteer scheduling and worship planninng system also?

I lean towards 'no' personally, esp. when so many churches already use PlanningCenterOnline.com for service planning.

**Comment by khebbie** [comment]
Yes I do realize that you will be in a kind of conflict since it would be a competitor to PlanningCenterOnline.com which I believe you work for?
But for at small church such the one I attend, where we are no more than a 100 members a solution like this would make sense.

If I should choose to make another rails (or phoenix) app do you see a way of integrating these two together?

**Comment by seven1m** [comment]
@khebbie I'm most worried about spreading our little team too thin. Perhaps a separate app would be a better idea.

If you do wish to build a separate app that uses OneBody's existing backend for authentication, you could look into using our authentication api: https://github.com/churchio/onebody/wiki/Authentication-API

If it isn't powerful enough, I'd be happy to work on it to provide what you need.
