### ISSUE TITLE
Suggestion: A more common language?

### ISSUE THREAD

**Issue by klarkc** [churchio/onebody#539]
I was thinking about a Javascript frontend with NodeJS support port. That's is nice because anyone who works on web projects, today, can help with this project. I want to help making things but I really don't know how to write a single line of ruby (and rails).

That said, I know it's a huge work to port a entire software to another language, but I want to help if I could. I am studying the entire javascript stack, from frontend (with Google's Polymer) to backend (I am choosing Loopback framework for while). With today's technology we can write a single application code shared between the server and client, and with Polymer, this code can even be used seamless as an native App on mobile clients.

What do you guys think about this?

**Comment by seven1m** [comment]
@klarkc Thanks for the suggestion. But no, we won't be porting OneBody to JavaScript any time soon.

I think there are some interesting things happening in the JavaScript/Node.js world, but Rails is a mature framework optimized for CRUD apps like this.

That being said, if you want to help out with a JavaScript application, definitely checkout [Cedar](https://github.com/cedarsuite/cedarserver) which is a Meteor app being built by our friend Isaac Smith.

**Comment by seven1m** [comment]
@klarkc In thinking about this some more, I wanted to say there is a lot of front-end work that can be done in OneBody without touching the Ruby backend. The new check-in frontend UI is written entirely with React.js and still has a ways to go. I'd love some help! <3
