### ISSUE TITLE
Amazon AMI not found 

### ISSUE THREAD

**Issue by kenazk** [churchio/onebody#544]
Hi there, I can't seem to find the AMI prescribed in the installation instructions. 

![image](https://cloud.githubusercontent.com/assets/1482985/9918510/1e3f03e4-5c7c-11e5-819f-7ff711198a81.png)

**Comment by cessien** [comment]
Hi! What region are you in???

**Comment by cessien** [comment]
Sorry what region did you select*

**Comment by kenazk** [comment]
Oh, you're right. I was in West US (Oregon). Thanks!
