### ISSUE TITLE
Add an online giving feature

### ISSUE THREAD

**Issue by pgmcgee** [churchio/onebody#546]
It would be great if churches could use OneBody to support their online giving.

**Comment by pgmcgee** [comment]
I'm currently working on this: https://github.com/pgmcgee/onebody/tree/giving

**Comment by seven1m** [comment]
@pgmcgee please let us know if you need any help!

**Comment by pgmcgee** [comment]
Some discussion of this feature: https://github.com/churchio/onebody/wiki/Roadmap:-Giving

**Comment by pgmcgee** [comment]
Documentation of the feature as it currently stands: https://github.com/churchio/onebody/wiki/Giving

**Comment by seven1m** [comment]
Sweet! ❤️💛💚💙

**Comment by andrewwippler** [comment]
Do you need help refactoring your code to allow for multiple payment processors? Right now you have stripe, but with a few improvements, we can get it ready for others (and thus merge this into master)

**Comment by pgmcgee** [comment]
I would love some help. If you do, let's branch it off the giving branch so that we don't block that work for the refactoring work.

**Comment by seven1m** [comment]
I'm going to close this for now as I don't think anyone is actively working on it and I'm trying to clean up the (very long) issues list.
