### ISSUE TITLE
Deleted Families Showing Up On Directory Map

### ISSUE THREAD

**Issue by dokuhebi** [churchio/onebody#549]
I noticed that on our directory map (https://host/directory_maps), that it's showing families that have been deleted from the site.  Not a major security issue, but it could potentially cause some privacy issues.

**Comment by dokuhebi** [comment]
FYI, purging the families does remove them from the map.  This is our current workaround.

**Comment by seven1m** [comment]
Yikes! Yep it shouldn't include families with the `deleted=true` attribute. I fixed it on master. Will be in the next release.

Thanks!
