### ISSUE TITLE
Message should allow a message without body if it has an html body

### ISSUE THREAD

**Issue by acbilimoria** [churchio/onebody#554]
[Coveralls] Set up the SimpleCov formatter.
[Coveralls] Using SimpleCov's default settings.
Run options: include {:focus=>true}

All examples were filtered out; ignoring {:focus=>true}

Randomized with seed 60638
...F.............^C
RSpec is shutting down and will print the summary report... Interrupt again to force quit.
.

Failures:

  1) Message should allow a message without body if it has an html body
     Failure/Error: @message = Message.create(subject: 'foo', html_body: 'bar', person: @person, group: @group)
     ActiveRecord::StatementInvalid:
       Mysql2::Error: Field 'body' doesn't have a default value: INSERT INTO `messages` (`site_id`, `subject`, `html_body`, `person_id`, `group_id`, `created_at`, `updated_at`, `code`) VALUES (1, 'foo', 'bar', 8, 2, '2015-09-27 19:05:13', '2015-09-27 19:05:13', 261568)

**Comment by seven1m** [comment]
@acbilimoria this works on my local box, at least with MySQL. Looking at the schema.rb, the `messages` table should allow nulls for the `body` column. Are you using Postgres perhaps?

**Comment by acbilimoria** [comment]
I'm using MySQL, but from what I was reading it sounded like the most
likely cause is a local setting in my.cnf / my.ini.  Should I close the
issue since its most likely not a real issue?

@acbilimoria <https://github.com/acbilimoria> this works on my local box,
at least with MySQL. Looking at the schema.rb, the messages table should
allow nulls for the body column. Are you using Postgres perhaps?

—
Reply to this email directly or view it on GitHub
<https://github.com/churchio/onebody/issues/554#issuecomment-144061466>.

**Comment by seven1m** [comment]
Don't close it. Let's try to figure this out. I've not heard of this issue before, but would like to know what the cause is!

**Comment by acbilimoria** [comment]
Yeah, neither have I!  It could be that my schema.rb doesn't allow body to be null:      
t.text     "body",         limit: 65535

**Comment by cessien** [comment]
This may be completely unrelated but I used to see issues like this at my old job. You might have to explicitly mark the body field as html safe http://stackoverflow.com/questions/10420240/mark-activerecord-attribute-as-html-safe

XSS (cross site scripting) prevention on active record may be stripping<html> it out and leaving the string null

#My2Cents

**Comment by seven1m** [comment]
@acbilimoria I'm pretty sure that `null: false` means null is not allowed. Without that, null *is* allowed. Can you do a `describe messages` in your database and post the result here?

**Comment by acbilimoria** [comment]
Sure:

**Comment by seven1m** [comment]
Thanks!

Do you think this bug report is the same issue? http://bugs.mysql.com/bug.php?id=14306

If so, I will playa round with the different modes and see if I can reproduce.

Are you running MySQL on Windows by chance?

**Comment by acbilimoria** [comment]
Yeah that bug looks similar to what I was seeing on stackoverflow, but I'm using Linux instead of Windows.

**Comment by seven1m** [comment]
@acbilimoria can you try setting this in your my.ini file:

```
sql-mode="NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
``

Does that fix it?

**Comment by acbilimoria** [comment]
Yep!  Works like a charm

**Comment by seven1m** [comment]
Yay. I'm going to close this. If someone else has this problem, we can point them here. Thanks @acbilimoria!
