### ISSUE TITLE
API v2

### ISSUE THREAD

**Issue by seven1m** [churchio/onebody#556]
This issue is a placeholder for the initial setup work on the v2 API. Some plans include:
- [x] Conform to [JSON API](http://jsonapi.org/)
- [ ] Support OAuth2
- [x] Namespace API separately from regular Rails controllers
- [x] One or two sample endpoints

Once these checkboxes are checked, we'll close this ticket (though work on the API will continue in small chunks).

**Comment by seven1m** [comment]
@buob FYI

**Comment by davidleach** [comment]
@seven1m I've got a good start on this.  I just need to complete a few more of the more common models and then I'll push it up for review.

**Comment by seven1m** [comment]
Yay!!!

**Comment by buob** [comment]
Hey @davidleach!  Any progress on this? :dancers:

**Comment by davidleach** [comment]
@buob yes, but not in the last couple of weeks.  Had some family stuff come up.  I'll try to push what I have in the next few days so if anyone else wants to jump in they can.

**Comment by davidleach** [comment]
@seven1m In our checklist, would request specs fulfill the sample endpoints requirement?

**Comment by seven1m** [comment]
@davidleach absolutely. I was just saying it needs to expose _something_, which you've already done in your branch.

**Comment by seven1m** [comment]
Closing this in favor of tracking the work on the PR #650....

Many thanks to @davidleach for getting this 80% of the way!!
