### ISSUE TITLE
Privacy Page Staff contact email malformed

### ISSUE THREAD

**Issue by hooray4me** [churchio/onebody#560]
The link hovers correctly, but displays incorrecty
![image](https://cloud.githubusercontent.com/assets/12399138/10264397/06ec36ba-69d0-11e5-9cac-fe4d86568502.png)

**Comment by seven1m** [comment]
@hooray4me this is fixed in the default template.

If you wish to update your page on an existing site, you can manually fix the issues, or you can delete and recreate the page from the template like this:

```
cd /var/www/onebody
rails console
page = Page.where(slug: 'privacy_policy').first
page.system = false
page.destroy
Site.current.add_pages
```
