### ISSUE TITLE
Technical Support contact missing from help

### ISSUE THREAD

**Issue by hooray4me** [churchio/onebody#561]
Can we put the technical contact email address specified in site setting on the help page?
![image](https://cloud.githubusercontent.com/assets/12399138/10264418/6fb2fed6-69d0-11e5-8917-eb7922381e14.png)
![image](https://cloud.githubusercontent.com/assets/12399138/10264422/a314f004-69d0-11e5-855f-733b81693d1d.png)

**Comment by seven1m** [comment]
@hooray4me that's a great idea. We can add that to the default help template.

FYI you can also edit this page in your admin console to include whatever you want!
