### ISSUE TITLE
Export Directory to Excel

### ISSUE THREAD

**Issue by hooray4me** [churchio/onebody#563]
My wife just got back from her Alter Society meeting with a request... Our church, as well as many others, do mass mailing... Can we add a function/button to export the directory to excel/csv so it can be used with a mail merge function to do mass mailings? Maybe it could be an admin/assignable role?

**Comment by seven1m** [comment]
We have CSV export already, in the Admin dashboard.

<img width="241" alt="screen shot 2015-10-05 at 9 34 01 pm" src="https://cloud.githubusercontent.com/assets/669/10300246/d2171060-6ba8-11e5-99a7-11425141cb30.png">

Let me know if this is what you're talking about.

**Comment by seven1m** [comment]
You can also give the permission to export to any admin:

<img width="609" alt="export_data" src="https://cloud.githubusercontent.com/assets/669/10311626/612962dc-6bfc-11e5-8b6d-76c43e2ceed7.png">

**Comment by seven1m** [comment]
Closing this. Reopen if there's something I'm misunderstanding here!
