### ISSUE TITLE
Ability to send emails to addresses as bcc rather than to

### ISSUE THREAD

**Issue by juanpaulo** [churchio/onebody#565]
Our church recently started using Church.IO and it has helped our members share prayer requests (and answered ones) better. As some prayers are more confidential than others, we thought that an option to send notifications to addressees in a more undisclosed way would be a good feature. In most cases, people who receive such notifications do not need to know who else received the prayer request.

**Comment by cessien** [comment]
I think the base assumptions currently for prayer requests is that it shared with the group you're in. Are you looking for more granular control then that?

**Comment by seven1m** [comment]
Group emails are sent with a single To address. What is disclosed in a group email?

**Comment by juanpaulo** [comment]
Sorry, I think what I wrote earlier was a bit misleading.
Currently, when someone makes a New Prayer Request and checks *Send as email to group members.* I receive the prayer request (which is great) but also the name and email address of each member of the group. For privacy, we were wondering if the email could be sent to each member as *bcc* rather than *to* to hide the email addresses.

**Comment by cessien** [comment]
Oh dang @seven1m @juanpaulo you are indeed right, it exposes the email addresses of the recipients, which I don't think is intended.

**Comment by seven1m** [comment]
Definitely not intended. It should send in the same way a group message does.

**Comment by cessien** [comment]
Correct me if I'm wrong but the code https://github.com/churchio/onebody/blob/master/app/models/notifier.rb#L53-L57
should be using the Message model like so https://github.com/churchio/onebody/blob/master/app/models/notifier.rb#L258-L273

**Comment by seven1m** [comment]
@cessien I'm not sure about that. I'll take a look at it soon.
