### ISSUE TITLE
Japanese translation

### ISSUE THREAD

**Issue by juanpaulo** [churchio/onebody#567]
Hello again. I can help translate onebody to Japanese and/or moderate if others want to contribute.

**Comment by seven1m** [comment]
Awesome! What is your email address? I'll add you to OneSky...

**Comment by juanpaulo** [comment]
juanpaulo.gutierrez@gmail.com

**Comment by seven1m** [comment]
I'm closing all the translation issues to get our bug list down to something workable. Closing this issue does **not** mean we are not continuing to work on (or encourage work on) translations of OneBody -- it only means that we won't track that progress in an issue (OneSky has a better system for tracking progress). Thanks!
