### ISSUE TITLE
Rewrite the Printed Directory feature

### ISSUE THREAD

**Issue by seven1m** [churchio/onebody#573]
The old code is really bad, and it uses an abandoned library called pdf-writer.

I'd like to rewrite the printed directory stuff using [Prawn](https://github.com/prawnpdf/prawn).

**Comment by notdodgy** [comment]
Entries are excluded from the printed directory if there is no home phone number or parts of the address are missing.
There is a profile option to enable inclusion in the printed directory.

I suggest making this the only control over inclusion or not.  
Reason being that many people now just use mobiles and do not have a home phone number.
Also addresses may be incomplete for a number of valid reasons.

**Comment by seven1m** [comment]
:+1:
