### ISSUE TITLE
Testimony page is broken with new AdminLTE template

### ISSUE THREAD

**Issue by seven1m** [churchio/onebody#576]

**Comment by cessien** [comment]
Oh dear... Is there a screenshot I could see? Everything looks okay on my end (the instance i'm using is a few commits behind)

**Comment by seven1m** [comment]
Aorry @cessien I just logged this quickly so I wouldn't forget. Forgot to invlude details.

Upload a large profile photo to your profile, then visit the testimony page. The photo overlaps the text.

This happens on some other pages as well, but I don't remember which ones.

**Comment by seven1m** [comment]
Fixed in 21291af14dc94df97e4347c5689568750901e0b9
