### ISSUE TITLE
Sort by recently added

### ISSUE THREAD

**Issue by buob** [churchio/onebody#578]
And perhaps by other criteria, or a way to filter by "new members."

**Comment by andrewwippler** [comment]
I think this would better be implemented in a report - something that would get emailed often.

The question to ask is, what defines a "new member"? Recently added to the database, a special member tag, or completing a "Introduction to the Church" class?

**Comment by seven1m** [comment]
Good idea, but going to close as I don't have any intention of working on this right now and I'd like to get our list of issues down to something manageable. Reopen if one of you guys want to take a stab at it...
