### ISSUE TITLE
I saw there still need some translation on Chinese

### ISSUE THREAD

**Issue by Davidzhu001** [churchio/onebody#579]
Is there anyone doing it?

**Comment by seven1m** [comment]
Yes, see #247. Let me know if you want to help out... I can add you to the project on OneSky.

**Comment by Davidzhu001** [comment]
Yep, i would love to help out!

**Comment by seven1m** [comment]
Great! I sent you an invite.

**Comment by Davidzhu001** [comment]
thanks
