### ISSUE TITLE
Check-in failing tests

### ISSUE THREAD

**Issue by andrewwippler** [churchio/onebody#581]
Failures:

  1) CheckinPresenter#times given a recurring time in the morning queried at night returns the recurring time
     Failure/Error: expect(subject.times.to_a).to eq([checkin_time])
       
       expected: [#<CheckinTime id: 6, weekday: 0, time: 900, the_datetime: nil, site_id: 1, created_at: "2016-01-08 12:40:24", updated_at: "2016-01-08 12:40:24", campus: "Main">]
            got: []
       
       (compared using ==)
       
       Diff:
       @@ -1,10 +1,2 @@
       -[#<CheckinTime:0x00559ce3978ff8
       -  id: 6,
       -  weekday: 0,
       -  time: 900,
       -  the_datetime: nil,
       -  site_id: 1,
       -  created_at: Fri, 08 Jan 2016 06:40:24 CST -06:00,
       -  updated_at: Fri, 08 Jan 2016 06:40:24 CST -06:00,
       -  campus: "Main">]
       +[]
       
     # ./spec/presenters/checkin_presenter_spec.rb:34:in `block (5 levels) in <top (required)>'

  2) CheckinPresenter#times given a recurring time at night queried at night returns the recurring time
     Failure/Error: expect(subject.times.to_a).to eq([checkin_time])
       
       expected: [#<CheckinTime id: 10, weekday: 0, time: 2330, the_datetime: nil, site_id: 1, created_at: "2016-01-08 12:40:25", updated_at: "2016-01-08 12:40:25", campus: "Main">]
            got: []
       
       (compared using ==)
       
       Diff:
       @@ -1,10 +1,2 @@
       -[#<CheckinTime:0x00559ce58269a0
       -  id: 10,
       -  weekday: 0,
       -  time: 2330,
       -  the_datetime: nil,
       -  site_id: 1,
       -  created_at: Fri, 08 Jan 2016 06:40:25 CST -06:00,
       -  updated_at: Fri, 08 Jan 2016 06:40:25 CST -06:00,
       -  campus: "Main">]
       +[]
       
     # ./spec/presenters/checkin_presenter_spec.rb:68:in `block (5 levels) in <top (required)>'

Finished in 6 minutes 4 seconds (files took 7.02 seconds to load)
1347 examples, 2 failures

Failed examples:

rspec ./spec/presenters/checkin_presenter_spec.rb:33 # CheckinPresenter#times given a recurring time in the morning queried at night returns the recurring time
rspec ./spec/presenters/checkin_presenter_spec.rb:67 # CheckinPresenter#times given a recurring time at night queried at night returns the recurring time

**Comment by seven1m** [comment]
@andrewwippler I cannot reproduce this. Can you check again on the latest master branch and see if this is still happening? (Reopen if it is.)
