### ISSUE TITLE
Audit trail

### ISSUE THREAD

**Issue by andrewwippler** [churchio/onebody#586]
It would be nice if an audit trail were added so admins could keep track of changes rather than each change be submitted to a secretary to approve.

For example, suppose `Person A` changes `Family B`'s address from `1233 W Ave J-8` to `1233 Ave J-8`. Since `1233 E Ave J-8` exists, Google maps will suggest both addresses as being the possible location. Staff looking at the address will have 50% success rate in sending a letter or visiting the home. If auditing were implemented, admins could see the change and manually revert the issue. It could also be helpful if there was a name change or an incorrect adjustment.

I am thinking this would encompass a new table with the following columns:
id, change_done_by, change_done_on, new_value, previous_value, created_at, updated_at

Edit methods would have to be refactored to be similar to the following:
```
def edit
...
change = AuditChange.create(:change_done_by => 'logged_in_user', :change_done_on => person.id, :previous_value => 'value', :new_value => 'new')
change.save
person.save
...
end
```

We could then list changes made to that person/family on their record by doing a query to their person id.

**Comment by seven1m** [comment]
@andrewwippler thanks for posting this, and I kind of think someday this would be nice, but I don't see it happening in the short term.

I'd like to close this issue for now in order to limit our issue list to things that are being worked on or will be worked on very shortly. We can revisit a bit down the road.
