### ISSUE TITLE
Feature Request: Sort directory by name or family (household)

### ISSUE THREAD

**Issue by andytruett** [churchio/onebody#595]
It'd be great to be able to sort the online directory either ascending or descending, by name or family/household!

**Comment by seven1m** [comment]
Yeah, this would be nice. @andytruett are you going to work on this?

**Comment by andytruett** [comment]
Unfortunately I am back to a busy season and would be rather slower than I'd like to get it done. I'll tinker in the time I have, but if anyone beats me to it, no biggie.

**Comment by seven1m** [comment]
Done!
