### ISSUE TITLE
Map Display Reveals Private Address Information

### ISSUE THREAD

**Issue by play4god** [churchio/onebody#596]
Hi, everyone...

I discovered tonight that, even if you set a user's privacy, and all family members' privacy settings to hide the address, address information is still displayed in these circumstances for non-admin users with 'Full Access':

- [x] Click Directory Map - drill in - click a pin - you can see the name of the person living on that street.  I suggest that pins shouldn't show for people whose address is hidden.

- [ ] Go to the directory, and choose a person (any person) whose address is hidden.  So far so good.  Now, click their family.  Look at the map at the top of the page.  It shows both the location pin, and if you click it, their full exact address.

Tim asked me to enter this as a bug here, so here goes. Let me know if you need more info.

Thanks,
Jeff

**Comment by seven1m** [comment]
@play4god thanks for reporting! We'll get this fixed before the next release.

**Comment by play4god** [comment]
Super!  Thanks!!

-Jeff

**Comment by seven1m** [comment]
This was fixed in ed643b6.

**Comment by play4god** [comment]
Thanks, Tim! :)  How can I apply the update?  Sorry - I’m new at this. :)
Jeff

**Comment by seven1m** [comment]
@play4god jump in Slack chat and I or someone else can help you. http://chat.church.io/

**Comment by seven1m** [comment]
Item number one was fixed, but not number two. Reopening.

**Comment by play4god** [comment]
More thoughts on this one - not sure the best way to decide when to show the map, since there are no family-specific privacy settings.  Is the family map only enabled when all family members have their preference to show it?  Or better yet - should there be privacy settings the family object itself?
Just some thoughts.

**Comment by seven1m** [comment]
Fixed on master.
