### ISSUE TITLE
Feature Request: Separate login and new user registration choices

### ISSUE THREAD

**Issue by play4god** [churchio/onebody#597]
Hi, all...

I wanted to suggest something for a use case we have.

Would it be possible to provide a login dialog both *without* the Create an Account selection, and another where it can be turned on (based on URL or query parm)?

We would like to approve all new accounts (that works great as-is), but we are also going to embed onebody in our mobile app.  Since anyone can download the mobile app, we'd like the mobile login to have 'sign me in' and 'I forgot', but we don't want anyone anywhere downloading the mobile app and attempting to create an account.

Then, at our church, we'd like to have a kiosk set up there, with the login dialog, and 'Create an Account' enabled.

That is, we want to ensure those requesting accounts are actually people with whom we have an on-location relationship.

Seems like a simple flag or option in settings to 'Include Create an Account on Login Dialog' could control the presence of the button... Then perhaps a separate URL or query parm on the main URL to force the option on for other situations...

Thoughts?

Thanks!
Jeff

**Comment by seven1m** [comment]
@play4god while this sounds like a neat idea, I don't know how you would make something like that secure. Once someone figured out the query param, then they could create an account from anywhere.

Here's what I'd do:

* Turn off account creation. This makes your mobile app work as desired.
* For your kiosk, build a custom app that uses the OneBody API to create an account.

I'm going to close this as I don't think it's something we can build in to the software directly. **BUT** this is the beauty of open source! You can hack on the software, build plugins, fork it, whatever you need!

**Comment by play4god** [comment]
Thanks, Tim. I ask because we are moving to one body from another platform.  They provide a kiosk signup page that allows this - that page now that I think of it is password protected to access it - so an admin can start it on the kiosk/ so addresses the concern you expressed that anyone with the address could use it. 

Would that approach work better?

-Jeff

**Comment by seven1m** [comment]
🤔
