### ISSUE TITLE
Strengthen password requirements

### ISSUE THREAD

**Issue by notdodgy** [churchio/onebody#600]
- [ ] Add an admin configurable option for minimum password length. Change default length to 6.
- [ ] Add the [strong_password](https://github.com/bdmac/strong_password) gem, but only enable with an Admin configuration option, and disable by default.

**Comment by seven1m** [comment]
@notdodgy thanks, this is a good idea! I updated the ticket description based on what I think we should do and marked the ticket as ready in case someone wants to make it happen.

**Comment by DrSayre** [comment]
@seven1m I can do this.  I have been wanting to get involved more in open source and this seems straight forward enough to start with.  As far as strong_password goes, were you thinking of just using the basic option of setting password_strength to true if the Admin has it turned on?

**Comment by seven1m** [comment]
@DrSayre that'd be great! Jump in chat and let us know if you need help!

Your solution sounds good.

**Comment by seven1m** [comment]
Finished in #627.
