### ISSUE TITLE
User photo is blurry when viewing a message

### ISSUE THREAD

**Issue by hooray4me** [churchio/onebody#601]
User photo is blurry when viewing a message sent to a group. 
![image](https://cloud.githubusercontent.com/assets/12399138/13901871/28f7df98-ee00-11e5-8186-d00d1cbb2bfd.png)

**Comment by seven1m** [comment]
Hmm, I see it too! Should be an easy fix.

**Comment by seven1m** [comment]
Fixed in #602!
