### ISSUE TITLE
Default privacy settings not applied for new user.

### ISSUE THREAD

**Issue by play4god** [churchio/onebody#605]
I'm currently using version 3.6.0-pre, however also saw this issue in 3.5.0.
Admin settings are set to have the following privacy sharing settings on for new accounts, and all other off:
Share Anniversary
Share Birthday

After new account creation, the Privacy settings are:

## Family

- Visible

## User

- Activity
- Anniversary
- Address
- Home Phone 
- Birthday

So it looks like the admin settings are not being honored.

**Comment by seven1m** [comment]
I believe this is fixed. I just tested by changing the default privacy settings and creating a new person. Worked!
