### ISSUE TITLE
Not sending changes emails, but sending "Verify Email"

### ISSUE THREAD

**Issue by pherzogchc** [churchio/onebody#606]
Onebody 3.5.0 on digitalocean using mailgun freshly installed on April 18
"Verify Email" emails are being sent and received but I am not seeing emails sent on Mailgun logs when users change their contact information.  I have tried changing the email addresses in the **Send Email Changes to** and **Send Updates to** field and also enabled **Updates Must Be Approved**.  I confirmed with DigitalOcean they are not blocking SMTP ports for my droplet.

**Comment by pherzogchc** [comment]
Should I expect to see something in the log for emails be sent -- like "email_update" being called?

I, [2016-04-28T16:22:44.458921 #9323]  INFO -- : Completed 200 OK in 146ms (Views: 126.5ms | ActiveRecord: 4.8ms)
I, [2016-04-28T16:23:01.820304 #9323]  INFO -- : Started PATCH "/people/713" for 127.0.0.1 at 2016-04-28 16:23:01 -0400
I, [2016-04-28T16:23:01.824033 #9323]  INFO -- : Processing by PeopleController#update as HTML
I, [2016-04-28T16:23:01.824276 #9323]  INFO -- :   Parameters: {"utf8"=>"✓", "authenticity_token"=>"G1BgGN8i9aZnKjhg9W0BQ5bpn3YySPv+E0UejorUd6wH+n6PkNbUDjXVXSfw272LaA15OL7Osh52/yOUuP59VA==", "person"=>{"first_name"=>"TESTS", "last_name"=>"USERS", "suffix"=>"", "description"=>"", "gender"=>"Male", "email"=>"peterh@chapelhillchurch.com", "mobile_phone"=>"6123094512", "work_phone"=>"", "fax"=>"", "birthday"=>"", "anniversary"=>"", "facebook_url"=>"", "twitter"=>"", "website"=>"", "testimony"=>"", "about"=>""}, "family"=>{"name"=>"TEST USER", "last_name"=>"USER", "home_phone"=>"", "address1"=>"4524 1st Ave S", "address2"=>"", "city"=>"Minneapolis", "state"=>"MN", "zip"=>"55122", "country"=>"US"}, "button"=>"", "id"=>"713"}
I, [2016-04-28T16:23:01.946034 #9323]  INFO -- : Redirected to http://onebody/people/713
I, [2016-04-28T16:23:01.946266 #9323]  INFO -- : Completed 302 Found in 122ms (ActiveRecord: 9.9ms)
I, [2016-04-28T16:23:02.025827 #9323]  INFO -- : Started GET "/people/713" for 127.0.0.1 at 2016-04-28 16:23:02 -0400
I, [2016-04-28T16:23:02.029428 #9323]  INFO -- : Processing by PeopleController#show as HTML
I, [2016-04-28T16:23:02.029607 #9323]  INFO -- :   Parameters: {"id"=>"713"}
I, [2016-04-28T16:23:02.064881 #9323]  INFO -- :   Rendered groups/_person_groups.haml (6.2ms)
I, [2016-04-28T16:23:02.065286 #9323]  INFO -- :   Rendered people/show_limited.html.haml within layouts/default (11.2ms)
I, [2016-04-28T16:23:02.068714 #9323]  INFO -- :   Rendered layouts/_favicons.haml (0.9ms)
I, [2016-04-28T16:23:02.075278 #9323]  INFO -- :   Rendered layouts/_navbar_right.haml (3.7ms)
I, [2016-04-28T16:23:02.127716 #9323]  INFO -- :   Rendered layouts/_footer_links.haml (1.3ms)
I, [2016-04-28T16:23:02.129627 #9323]  INFO -- : Completed 200 OK in 100ms (Views: 72.5ms | ActiveRecord: 5.5ms)

**Comment by seven1m** [comment]
@pherzogchc I'm embarrassed to say this has been broken for a long time. 😢 

I just pushed a commit to master that reinstates it.

**Comment by pherzogchc** [comment]
YES!  Thanks Tim!
