### ISSUE TITLE
Cannot Access Admin - after manual install on digitalocean

### ISSUE THREAD

**Issue by warain** [churchio/onebody#607]
The site works well, but I am not able to access admin section
I get a 500 internal error - by site is install in a subdomain folder, members.domain.org

This is the error i get when I visit https://members.domain.com

Error
We're sorry, but something went wrong.
We've been notified about this issue and we'll take a look at it shortly.

Any help would be greatly appreciated.

Thanks

**Comment by seven1m** [comment]
Sorry this is an issue with permissions. Check out #476 for the solution.
