### ISSUE TITLE
Validation: /app/models/custom_report.rb

### ISSUE THREAD

**Issue by Newman101** [churchio/onebody#609]
Hi. Looks like the format validation in CustomReport is insufficient:

``` Ruby
  validates :filters, format: /:/, allow_blank: true
  validate :filter_content
```

Maybe there should be a bit more validation anchors to improve security? If needed, I can create PR for this.

Thank you.

**Comment by seven1m** [comment]
Oh, wow, you're right. This should never have been written this way. 😬 

I think a major rewrite of this code is in order. If you have the nerve to do it, please go for it. If not, I'll work on it. Thanks!

**Comment by Newman101** [comment]
Sure, I'll send PR as soon as possible. =)
