### ISSUE TITLE
Validation: /app/models/person.rb

### ISSUE THREAD

**Issue by Newman101** [churchio/onebody#611]
Another possible validation issue.

```Ruby
  validates :facebook_url,
            format: { with: %r{\Ahttps?\://www\.facebook\.com/.+} },
```

This one has beginning anchor but the closure is missing. As a consequence, users can fool this validation by inserting new lines into their username as the regular expression only checks the boundaries of a line and not the full text. Hence, this might be an another security issue.

**Comment by seven1m** [comment]
I don't see what makes that a security concern. Have you tried doing that on the site? The link that's generated wouldn't, as far as I can tell, do anything useful/harmful.

**Comment by Newman101** [comment]
Hi. Looks like this is not a concern after all. I think this one can be certainly closed.
