### ISSUE TITLE
Unprotected redirect: app/controllers/families_controller.rb

### ISSUE THREAD

**Issue by Newman101** [churchio/onebody#613]
Hi.

Looks like there is an unprotected re-direct in families_controller.rb:

```Ruby
    if @updater.save!
      respond_to do |format|
        format.html { flash[:notice] = t('families.edit.saved'); redirect_to params[:redirect_to] || @family }
        format.xml  { render xml: @family.to_xml } if can_export?
      end
```

The potential danger here is due to manipulation possibility of ```params``` which could contain something like this:

```Ruby
:host => 'evilsite.com'
```

Due to this danger, it would be wise to limit the redirections only to current host. 

Thanks.

**Comment by seven1m** [comment]
Thanks, we'll get that fixed.
