### ISSUE TITLE
Email Not Distributing to Group Email Addresses

### ISSUE THREAD

**Issue by internetjason** [churchio/onebody#628]
We've chatted on Slack, so I won't go into too many details. The bottom line is that I can send emails OUT of OneBody and they are delivered as expected (using Mailgun), but incoming emails to group addresses are not being distributed. 

Here's the production.log. 
I, [2016-07-18T13:50:59.216434 #30934]  INFO -- : Started POST "/emails.mime" for 127.0.0.1 at 2016-07-18 13:50:59 -0400
I, [2016-07-18T13:50:59.222866 #30934]  INFO -- : Processing by EmailsController#create as
I, [2016-07-18T13:50:59.223844 #30934]  INFO -- :   Parameters: {"recipient"=>"east@midtownpeople.org", "sender"=>"jason@midtownaustin.org", "subject"=>"test email", "from"=>"Jason Carroll <jason@midtownaustin.org>", "X-Mailgun-Incoming"=>"Yes", "X-Envelope-From"=>"<jason@midtownaustin.org>", "Received"=>"by 10.83.48.69 with HTTP; Mon, 18 Jul 2016 10:50:58 -0700 (PDT)", "Dkim-Signature"=>"v=1; a=rsa-sha256; c=relaxed/relaxed;        d=midtownaustin-org.20150623.gappssmtp.com; s=20150623;        h=mime-version:from:date:message-id:subject:to;        bh=dP6NRfiE4ntdY2eaGxx3YKVwTulViaJuHMLgbvjSsNw=;        b=qwO4iGXiEhauuM5/Pxi2bq37t0z56gPD49MlP9myDewI2WczV/60XN7L1zCQaMZ18f         ek+JdfXt6siMKW0L32x/hL5c2VFaSxtKYQ431bgnxA2ss1QFf8ti+pAhgF3GkLjWh+gX         9cwWiPWSGaAcGWcrZ7nQbzdv1/DM9/dWNAuHSPFwzct8jsjeUM16xXL4TL3+78Xvh34y         o5qaBthDKvrR9KZXWB1ixba0SvgAzvKoCi+ThUJvVFfUYuQIvciNt+I53vGoK81RDXq/         IAfZCmU9nfvFWfBhhFmOS64mXF8UTxH2+VGSid4CTxvX+8sVbNbhiv4LYj0JbiYjS9wA         u82g==", "X-Google-Dkim-Signature"=>"v=1; a=rsa-sha256; c=relaxed/relaxed;        d=1e100.net; s=20130820;        h=x-gm-message-state:mime-version:from:date:message-id:subject:to;        bh=dP6NRfiE4ntdY2eaGxx3YKVwTulViaJuHMLgbvjSsNw=;        b=bgd4m0T6DlX6M28EhVGjDhbtmkdG+nmZlf7KYfeltXLPDX7ZDp2Hlb4O7nPBRsvoOi         eRGrid3itx1xB7LthR/CPJFC3YAsBGzOGfiL5kd5oGbt41ygNf1ajWptjVE1Plz/fatv         tDiPQ4lOH+pxZ1S93poIG6SNcQZUmQj3U+ySr8rvO9n5wWatlCoqqrInuIepUU82GJ+U         eOpeDOptHy2d9GrMXEadzDTVw3f/gME5PuzR1K5HgjveOUwMcSCT3cbvO0LVvxIqIbSj         sCaYe+TYEe3j3PhQ9nNj6Cb/Ep/sqPWr3t///sVKsrKpAk7IX2kaIT3wabZDXx6ZV3QS         crJw==", "X-Gm-Message-State"=>"ALyK8tJgbStVH1k2YymCaRA2fm//YTkI/SGHWD6/8nFoE1XwWJrKvOH8ZSSVK6MOppcs47eWtHsBGUB2iYDQ8g==", "X-Received"=>"by 10.37.3.129 with SMTP id 123mr4699059ybd.181.1468864258357; Mon, 18 Jul 2016 10:50:58 -0700 (PDT)", "Mime-Version"=>"1.0", "From"=>"Jason Carroll <jason@midtownaustin.org>", "Date"=>"Mon, 18 Jul 2016 12:50:58 -0500", "Message-Id"=>"<CAEATBak-itvy2PSS+ruM-u3cioGkzTCVqL6+d5k=MP7j=w7xcA@mail.gmail.com>", "Subject"=>"test email", "To"=>"east@midtownpeople.org", "Content-Type"=>"multipart/alternative; boundary=\"001a11c0219e57e0180537ec9c1b\"", "message-headers"=>"[[\"X-Mailgun-Incoming\", \"Yes\"], [\"X-Envelope-From\", \"<jason@midtownaustin.org>\"], [\"Received\", \"from mail-yw0-f195.google.com (mail-yw0-f195.google.com [209.85.161.195]) by mxa.mailgun.org with ESMTP id 578d1702.7fc3f06746f0-in01; Mon, 18 Jul 2016 17:50:58 -0000 (UTC)\"], [\"Received\", \"by mail-yw0-f195.google.com with SMTP id l125so12202688ywb.1        for <east@midtownpeople.org>; Mon, 18 Jul 2016 10:50:58 -0700 (PDT)\"], [\"Dkim-Signature\", \"v=1; a=rsa-sha256; c=relaxed/relaxed;        d=midtownaustin-org.20150623.gappssmtp.com; s=20150623;        h=mime-version:from:date:message-id:subject:to;        bh=dP6NRfiE4ntdY2eaGxx3YKVwTulViaJuHMLgbvjSsNw=;        b=qwO4iGXiEhauuM5/Pxi2bq37t0z56gPD49MlP9myDewI2WczV/60XN7L1zCQaMZ18f         ek+JdfXt6siMKW0L32x/hL5c2VFaSxtKYQ431bgnxA2ss1QFf8ti+pAhgF3GkLjWh+gX         9cwWiPWSGaAcGWcrZ7nQbzdv1/DM9/dWNAuHSPFwzct8jsjeUM16xXL4TL3+78Xvh34y         o5qaBthDKvrR9KZXWB1ixba0SvgAzvKoCi+ThUJvVFfUYuQIvciNt+I53vGoK81RDXq/         IAfZCmU9nfvFWfBhhFmOS64mXF8UTxH2+VGSid4CTxvX+8sVbNbhiv4LYj0JbiYjS9wA         u82g==\"], [\"X-Google-Dkim-Signature\", \"v=1; a=rsa-sha256; c=relaxed/relaxed;        d=1e100.net; s=20130820;        h=x-gm-message-state:mime-version:from:date:message-id:subject:to;        bh=dP6NRfiE4ntdY2eaGxx3YKVwTulViaJuHMLgbvjSsNw=;        b=bgd4m0T6DlX6M28EhVGjDhbtmkdG+nmZlf7KYfeltXLPDX7ZDp2Hlb4O7nPBRsvoOi         eRGrid3itx1xB7LthR/CPJFC3YAsBGzOGfiL5kd5oGbt41ygNf1ajWptjVE1Plz/fatv         tDiPQ4lOH+pxZ1S93poIG6SNcQZUmQj3U+ySr8rvO9n5wWatlCoqqrInuIepUU82GJ+U         eOpeDOptHy2d9GrMXEadzDTVw3f/gME5PuzR1K5HgjveOUwMcSCT3cbvO0LVvxIqIbSj         sCaYe+TYEe3j3PhQ9nNj6Cb/Ep/sqPWr3t///sVKsrKpAk7IX2kaIT3wabZDXx6ZV3QS         crJw==\"], [\"X-Gm-Message-State\", \"ALyK8tJgbStVH1k2YymCaRA2fm//YTkI/SGHWD6/8nFoE1XwWJrKvOH8ZSSVK6MOppcs47eWtHsBGUB2iYDQ8g==\"], [\"X-Received\", \"by 10.37.3.129 with SMTP id 123mr4699059ybd.181.1468864258357; Mon, 18 Jul 2016 10:50:58 -0700 (PDT)\"], [\"Mime-Version\", \"1.0\"], [\"Received\", \"by 10.83.48.69 with HTTP; Mon, 18 Jul 2016 10:50:58 -0700 (PDT)\"], [\"From\", \"Jason Carroll <jason@midtownaustin.org>\"], [\"Date\", \"Mon, 18 Jul 2016 12:50:58 -0500\"], [\"Message-Id\", \"<CAEATBak-itvy2PSS+ruM-u3cioGkzTCVqL6+d5k=MP7j=w7xcA@mail.gmail.com>\"], [\"Subject\", \"test email\"], [\"To\", \"east@midtownpeople.org\"], [\"Content-Type\", \"multipart/alternative; boundary=\\\"001a11c0219e57e0180537ec9c1b\\\"\"]]", "timestamp"=>"1468864259", "token"=>"88143a12b7eb41b4fc4f010683cfa12cbe605bc61661922a77", "signature"=>"d87927b5837037830977029e49ab1918d47686d644b80f8b48a2fa39a6365fa4", "body-mime"=>"X-Mailgun-Incoming: Yes\r\nX-Envelope-From: <jason@midtownaustin.org>\r\nReceived: from mail-yw0-f195.google.com (mail-yw0-f195.google.com [209.85.161.195])\n by mxa.mailgun.org with ESMTP id 578d1702.7fc3f06746f0-in01;\n Mon, 18 Jul 2016 17:50:58 -0000 (UTC)\r\nReceived: by mail-yw0-f195.google.com with SMTP id l125so12202688ywb.1\r\n        for <east@midtownpeople.org>; Mon, 18 Jul 2016 10:50:58 -0700 (PDT)\r\nDKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;\r\n        d=midtownaustin-org.20150623.gappssmtp.com; s=20150623;\r\n        h=mime-version:from:date:message-id:subject:to;\r\n        bh=dP6NRfiE4ntdY2eaGxx3YKVwTulViaJuHMLgbvjSsNw=;\r\n        b=qwO4iGXiEhauuM5/Pxi2bq37t0z56gPD49MlP9myDewI2WczV/60XN7L1zCQaMZ18f\r\n         ek+JdfXt6siMKW0L32x/hL5c2VFaSxtKYQ431bgnxA2ss1QFf8ti+pAhgF3GkLjWh+gX\r\n         9cwWiPWSGaAcGWcrZ7nQbzdv1/DM9/dWNAuHSPFwzct8jsjeUM16xXL4TL3+78Xvh34y\r\n         o5qaBthDKvrR9KZXWB1ixba0SvgAzvKoCi+ThUJvVFfUYuQIvciNt+I53vGoK81RDXq/\r\n         IAfZCmU9nfvFWfBhhFmOS64mXF8UTxH2+VGSid4CTxvX+8sVbNbhiv4LYj0JbiYjS9wA\r\n         u82g==\r\nX-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;\r\n        d=1e100.net; s=20130820;\r\n        h=x-gm-message-state:mime-version:from:date:message-id:subject:to;\r\n        bh=dP6NRfiE4ntdY2eaGxx3YKVwTulViaJuHMLgbvjSsNw=;\r\n        b=bgd4m0T6DlX6M28EhVGjDhbtmkdG+nmZlf7KYfeltXLPDX7ZDp2Hlb4O7nPBRsvoOi\r\n         eRGrid3itx1xB7LthR/CPJFC3YAsBGzOGfiL5kd5oGbt41ygNf1ajWptjVE1Plz/fatv\r\n         tDiPQ4lOH+pxZ1S93poIG6SNcQZUmQj3U+ySr8rvO9n5wWatlCoqqrInuIepUU82GJ+U\r\n         eOpeDOptHy2d9GrMXEadzDTVw3f/gME5PuzR1K5HgjveOUwMcSCT3cbvO0LVvxIqIbSj\r\n         sCaYe+TYEe3j3PhQ9nNj6Cb/Ep/sqPWr3t///sVKsrKpAk7IX2kaIT3wabZDXx6ZV3QS\r\n         crJw==\r\nX-Gm-Message-State: ALyK8tJgbStVH1k2YymCaRA2fm//YTkI/SGHWD6/8nFoE1XwWJrKvOH8ZSSVK6MOppcs47eWtHsBGUB2iYDQ8g==\r\nX-Received: by 10.37.3.129 with SMTP id 123mr4699059ybd.181.1468864258357;\r\n Mon, 18 Jul 2016 10:50:58 -0700 (PDT)\r\nMIME-Version: 1.0\r\nReceived: by 10.83.48.69 with HTTP; Mon, 18 Jul 2016 10:50:58 -0700 (PDT)\r\nFrom: Jason Carroll <jason@midtownaustin.org>\r\nDate: Mon, 18 Jul 2016 12:50:58 -0500\r\nMessage-ID: <CAEATBak-itvy2PSS+ruM-u3cioGkzTCVqL6+d5k=MP7j=w7xcA@mail.gmail.com>\r\nSubject: test email\r\nTo: east@midtownpeople.org\r\nContent-Type: multipart/alternative; boundary=001a11c0219e57e0180537ec9c1b\r\n\r\n--001a11c0219e57e0180537ec9c1b\r\nContent-Type: text/plain; charset=UTF-8\r\n\r\n\r\n\r\n--001a11c0219e57e0180537ec9c1b\r\nContent-Type: text/html; charset=UTF-8\r\n\r\n<div dir=\"ltr\"><br><div><div class=\"gmail_signature\" data-smartmail=\"gmail_signature\"><div dir=\"ltr\"><div></div></div></div></div>\r\n</div>\r\n\r\n--001a11c0219e57e0180537ec9c1b--"}
W, [2016-07-18T13:50:59.235629 #30934]  WARN -- : Can't verify CSRF token authenticity
I, [2016-07-18T13:50:59.237380 #30934]  INFO -- : Completed 422 Unprocessable Entity in 13ms (ActiveRecord: 0.5ms)
F, [2016-07-18T13:50:59.242588 #30934] FATAL -- :
ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken):
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.6/lib/action_controller/metal/request_forgery_protection.rb:181:in `handle_unverified_request'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.6/lib/action_controller/metal/request_forgery_protection.rb:209:in `handle_unverified_request'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.6/lib/action_controller/metal/request_forgery_protection.rb:204:in `verify_authenticity_token'
  vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:432:in `block in make_lambda'
  vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:145:in `call'
  vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:145:in `block in halting_and_conditional'
  vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:504:in `call'
  vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:504:in `block in call'
  vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:504:in `each'
  vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:504:in `call'
  vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
  vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
  vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:81:in `run_callbacks'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.6/lib/abstract_controller/callbacks.rb:19:in `process_action'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.6/lib/action_controller/metal/rescue.rb:29:in `process_action'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.6/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/notifications.rb:164:in `block in instrument'
  vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/notifications.rb:164:in `instrument'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.6/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.6/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.6/lib/abstract_controller/base.rb:137:in `process'
  vendor/bundle/ruby/2.2.0/gems/actionview-4.2.6/lib/action_view/rendering.rb:30:in `process'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.6/lib/action_controller/metal.rb:196:in `dispatch'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.6/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.6/lib/action_controller/metal.rb:237:in `block in action'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.6/lib/action_dispatch/routing/route_set.rb:74:in `call'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.6/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.6/lib/action_dispatch/routing/route_set.rb:43:in `serve'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.6/lib/action_dispatch/journey/router.rb:43:in `block in serve'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.6/lib/action_dispatch/journey/router.rb:30:in `each'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.6/lib/action_dispatch/journey/router.rb:30:in `serve'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.6/lib/action_dispatch/routing/route_set.rb:817:in `call'
  vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/2.2.0/gems/omniauth-1.3.1/lib/omniauth/strategy.rb:186:in `call!'
  vendor/bundle/ruby/2.2.0/gems/omniauth-1.3.1/lib/omniauth/strategy.rb:164:in `call'
  vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/2.2.0/gems/omniauth-1.3.1/lib/omniauth/builder.rb:63:in `call'
  vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.15.0.314/lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
  vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.15.0.314/lib/new_relic/rack/browser_monitoring.rb:32:in `traced_call'
  vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/etag.rb:24:in `call'
  vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/conditionalget.rb:38:in `call'
  vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
  vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/flash.rb:260:in `call'
  vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
  vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
  vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/cookies.rb:560:in `call'
  vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/query_cache.rb:36:in `call'
  vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:81:in `run_callbacks'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/rack/logger.rb:38:in `call_app'
  vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/rack/logger.rb:20:in `block in call'
  vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/tagged_logging.rb:68:in `block in tagged'
  vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/tagged_logging.rb:26:in `tagged'
  vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/tagged_logging.rb:68:in `tagged'
  vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/rack/logger.rb:20:in `call'
  vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/2.2.0/gems/request_store-1.3.0/lib/request_store/middleware.rb:9:in `call'
  vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/request_id.rb:21:in `call'
  vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
  vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
  vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/static.rb:120:in `call'
  vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
  vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/engine.rb:518:in `call'
  vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/application.rb:165:in `call'
  vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/2.2.0/gems/thin-1.6.4/lib/thin/connection.rb:86:in `block in pre_process'
  vendor/bundle/ruby/2.2.0/gems/thin-1.6.4/lib/thin/connection.rb:84:in `catch'
  vendor/bundle/ruby/2.2.0/gems/thin-1.6.4/lib/thin/connection.rb:84:in `pre_process'
  vendor/bundle/ruby/2.2.0/gems/thin-1.6.4/lib/thin/connection.rb:53:in `process'
  vendor/bundle/ruby/2.2.0/gems/thin-1.6.4/lib/thin/connection.rb:39:in `receive_data'
  vendor/bundle/ruby/2.2.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run_machine'
  vendor/bundle/ruby/2.2.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run'
  vendor/bundle/ruby/2.2.0/gems/thin-1.6.4/lib/thin/backends/base.rb:73:in `start'
  vendor/bundle/ruby/2.2.0/gems/thin-1.6.4/lib/thin/server.rb:162:in `start'
  vendor/bundle/ruby/2.2.0/gems/thin-1.6.4/lib/thin/controllers/controller.rb:87:in `start'
  vendor/bundle/ruby/2.2.0/gems/thin-1.6.4/lib/thin/runner.rb:200:in `run_command'
  vendor/bundle/ruby/2.2.0/gems/thin-1.6.4/lib/thin/runner.rb:156:in `run!'
  vendor/bundle/ruby/2.2.0/gems/thin-1.6.4/bin/thin:6:in `<top (required)>'
  vendor/bundle/ruby/2.2.0/bin/thin:23:in `load'
  vendor/bundle/ruby/2.2.0/bin/thin:23:in `<main>'

**Comment by seven1m** [comment]
This is fixed in master and should be fixed in the next nightly deb package.

**Comment by internetjason** [comment]
Thanks, Tim. I am not able to access the site now. It's doing the weird redirect to onebody instead of loading the site. I hope you're still working on it.

—
Jason Carroll
469-766-1041
Sent on the go
