### ISSUE TITLE
non-secure openstreetmaps elements loading on https site

### ISSUE THREAD

**Issue by internetjason** [churchio/onebody#630]
On pages like Groups, where maps are loading, the map images are not being loaded over a secure connection. 

`Mixed Content: The page at _link_ was loaded over HTTPS, but requested an insecure image http://a.tile.openstreetmap.org/13/1874/3372.png. This content should also be served over HTTPS.`

**Comment by hunternet93** [comment]
A simple fix would be to change the template to use the `//` URL syntax, i.e. [//a.tile.openstreetmap.org/13/1874/3372.png](//a.tile.openstreetmap.org/13/1874/3372.png), which tells the browser to use whichever protocol (http or https) the current page is using. I probably won't have time to make a PR for this in the next couple weeks though.

**Comment by seven1m** [comment]
@internetjason or @hunternet93 could one of you see if you can apply this fix?

**Comment by internetjason** [comment]
@seven1m I'm happy to try, but I need more detailed instructions on what you'd like me to do since I'm a super rookie.

**Comment by seven1m** [comment]
This should be fixed on master now!
