### ISSUE TITLE
CSV import fails when country field value is long

### ISSUE THREAD

**Issue by sherifkozman** [churchio/onebody#632]
Release : 3.5.0 

Import feature reported error when inserting long string into the country field (i.e.: United States of America)

Actor crashed!
ActiveRecord::StatementInvalid: Mysql2::Error: Data too long for column 'error_message' at row 1: UPDATE `imports` SET `status` = 101, `error_message` = 'Mysql2::Error: Data too long for column \'country\' at row 1: INSERT INTO `families` (`site_id`, `last_name`, `name`, `home_phone`, `address1`, `city`, `state`, `zip`, `country`, `updated_at`) VALUES (1, \’XXX\', \’XXXX\', \’00000000\', \’00 street name\', \'Irvine\', \'CA\', \'92603\', \'USA\', \'2016-09-06 20:45:50\')', `updated_at` = '2016-09-06 20:45:50' WHERE `imports`.`id` = XX

**Comment by andrewwippler** [comment]
According to https://github.com/churchio/onebody/blob/master/db/schema.rb#L203 there is a 2 character limit on the country field. The quick fix is to shorten the country code before you import it.

@seven1m Any reason why the app did not catch this before it imported it?

**Comment by seven1m** [comment]
Probably just need a validation on length of that attribute on the model.

**Comment by andrewwippler** [comment]
Ok, I will write this up.

**Comment by andrewwippler** [comment]
The import action is not going through the family model which has the restriction already in place. There would need to be a limitation on the import model - I just can't seem to find this location in the code.

I also noticed that the default settings allow for creation of a 3 character country code which would trigger this issue as well.

**Comment by seven1m** [comment]
@andrewwippler thanks for taking a stab at it.
