### ISSUE TITLE
updating a user password overrides email with the wrong value

### ISSUE THREAD

**Issue by sherifkozman** [churchio/onebody#633]
When manually trying to override or update another user password the email address field is overridden with the logged in user(admin) email ID rather than user's own email ID

Steps : 

- Log in as an Admin
- Choose any user to update
- Select Password from the profile menu
- User email field will display admin email value instead of the user email

**Comment by seven1m** [comment]
@sherifkozman I cannot reproduce this. Is it possible your browser is auto-completing the email address?

**Comment by sherifkozman** [comment]
@seven1m i did double check and confirmed its a Safari only issue which means its browser related, i am sorry for the hassle for everyone
