### ISSUE TITLE
(Removed person) doesn't get removed from group membership

### ISSUE THREAD

**Issue by sherifkozman** [churchio/onebody#647]
When deleting or removing a user (gets labeled as "Removed Person") , user details remains as a member of any of his previous groups memberships.

![group members](https://cloud.githubusercontent.com/assets/666788/19907347/b225358e-a03b-11e6-99cb-15ae3fe2a0be.jpg)
![removed person profile](https://cloud.githubusercontent.com/assets/666788/19907349/b28dc0d6-a03b-11e6-8927-1e77657b9feb.jpg)

**Comment by seven1m** [comment]
Hmmm, that's not supposed to happen! Here is the callback that is supposed to remove deleted people from groups: https://github.com/churchio/onebody/blob/master/app/models/concerns/person/memberships.rb#L12

**Comment by sherifkozman** [comment]
Would adding people to a group using the rails console bypass this and add
deleted persons as well?

group = Group.find(68)
Person.find_each { |p| group.memberships.create!(person: p) }

That's the only explanation I can think of or its some kind of fluke!

**Comment by seven1m** [comment]
Yes! That would totally do it! 😆

**Comment by sherifkozman** [comment]
Great
How would we identify "removed persons" when assigning group membership
then so they don't get added?

**Comment by seven1m** [comment]
`Person.undeleted.find_each` instead of `Person.find_each`. Sorry about that!
