### ISSUE TITLE
Web Interface In Error State After Vagrant Up

### ISSUE THREAD

**Issue by jandrusk** [churchio/onebody#652]
After following the directions on the Git home page, accessing http://localhost:8080 produces error: "We're sorry, but something went wrong.
The issue has been logged for investigation. Please try again later."

Host OS is Debian Stretch. Here is the technical dump from the page: 

Error:
Web application could not be started
Error ID:
2f97516a
Details:
An error occurred while starting up the preloader. It exited before signalling successful startup back to Phusion Passenger. Please read this article for more information about this problem.
Raw process output:

*** ERROR ***: Cannot execute /home/vagrant/.rvm/wrappers/ruby-2.3.1@onebody/ruby: No such file or directory (2)
System information:
Application root
/vagrant
Environment (value of RAILS_ENV, RACK_ENV, WSGI_ENV, NODE_ENV and PASSENGER_APP_ENV)
development
Ruby interpreter command
/home/vagrant/.rvm/wrappers/ruby-2.3.1@onebody/ruby
User and groups
uid=1000(vagrant) gid=1000(vagrant) groups=1000(vagrant),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),110(lpadmin),111(sambashare)
Environment variables
APACHE_PID_FILE=/var/run/apache2/apache2.pid
rvm_bin_path=/home/vagrant/.rvm/bin
GEM_HOME=/home/vagrant/.rvm/gems/ruby-2.3.1
SHELL=/bin/bash
APACHE_RUN_USER=www-data
IRBRC=/home/vagrant/.rvm/rubies/ruby-2.3.1/.irbrc
PASSENGER_DEBUG_DIR=/tmp/passenger.spawn-debug.XXXXyGuoF2
MY_RUBY_HOME=/home/vagrant/.rvm/rubies/ruby-2.3.1
rvm_stored_umask=0022
USER=vagrant
_system_type=Linux
rvm_path=/home/vagrant/.rvm
PASSENGER_USE_FEEDBACK_FD=true
rvm_prefix=/home/vagrant
APACHE_LOG_DIR=/var/log/apache2
PATH=/home/vagrant/.rvm/gems/ruby-2.3.1/bin:/home/vagrant/.rvm/gems/ruby-2.3.1@global/bin:/home/vagrant/.rvm/rubies/ruby-2.3.1/bin:/home/vagrant/.rvm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
rvm_loaded_flag=1
PWD=/vagrant
APACHE_RUN_GROUP=www-data
LANG=C
_system_arch=x86_64
_system_version=14.04
rvm_version=1.29.0 (latest)
SHLVL=0
HOME=/home/vagrant
rvm_ruby_string=ruby-2.3.1
LOGNAME=vagrant
SERVER_SOFTWARE=Apache/2.4.7 (Ubuntu) Phusion_Passenger/5.1.2
GEM_PATH=/home/vagrant/.rvm/gems/ruby-2.3.1:/home/vagrant/.rvm/gems/ruby-2.3.1@global
rvm_delete_flag=0
APACHE_LOCK_DIR=/var/lock/apache2
APACHE_RUN_DIR=/var/run/apache2
RUBY_VERSION=ruby-2.3.1
rvm_user_install_flag=1
_system_name=Ubuntu
IN_PASSENGER=1
PYTHONUNBUFFERED=1
NODE_PATH=/home/vagrant/.rvm/gems/ruby-2.3.1@global/gems/passenger-5.1.2/src/nodejs_supportlib
RAILS_ENV=development
RACK_ENV=development
WSGI_ENV=development
NODE_ENV=development
PASSENGER_APP_ENV=development
Ulimits
Unknown
System metrics
------------- General -------------
Kernel version    : 3.13.0-24-generic
Uptime            : 10m 41s
Load averages     : 0.00%, 0.02%, 0.02%
Fork rate         : unknown

------------- CPU -------------
Number of CPUs    :    2
Average CPU usage :   8%  --   8% user,   0% nice,   0% system,  92% idle
  CPU 1           :  17%  --  17% user,   0% nice,   0% system,  83% idle
  CPU 2           :   0%  --   0% user,   0% nice,   0% system, 100% idle
I/O pressure      :   0%
  CPU 1           :   0%
  CPU 2           :   0%
Interference from other VMs:   0%
  CPU 1                    :   0%
  CPU 2                    :   0%

------------- Memory -------------
RAM total         :    993 MB
RAM used          :    148 MB (15%)
RAM free          :    845 MB
Swap total        :   2991 MB
Swap used         :      0 MB (0%)
Swap free         :   2991 MB
Swap in           : unknown
Swap out          : unknown

**Comment by seven1m** [comment]
Thanks for reporting it!

**Comment by seven1m** [comment]
Here's how to fix your existing vagrant machine:

```
vagrant provision
```

If that doesn't work, you can do `vagrant destroy` followed by `vagrant up`.
