### ISSUE TITLE
Date Picker on Public Attendance page uses incorrect format

### ISSUE THREAD

**Issue by alexanderdixon** [churchio/onebody#664]
Using the following settings:

Full Date & Time: %d/%m/%Y %I:%M %p
Date: %d/%m/%Y

The dates appear to update correctly, however date picker on the public attendance page incorrectly assumes american date format. 

Incorrect operation (on public attendance page)
![image](https://cloud.githubusercontent.com/assets/13705283/24979543/7d11449e-1fcc-11e7-8c68-9e68a6657b9d.png)

Correct operation (on non public attendance page)
![image](https://cloud.githubusercontent.com/assets/13705283/24979569/9abc520e-1fcc-11e7-9956-b72d6476550d.png)

**Comment by seven1m** [comment]
Thanks for the bug report! This will be fixed in the next release.
