### ISSUE TITLE
Allow imported boolean fields to be interpreted in reverse

### ISSUE THREAD

**Issue by zarniwoop** [churchio/onebody#674]
As a PowerChurch user importing to OneBody from CSV,
I want OneBody to let me instruct it for boolean fields to read true from the CSV as false for the import and vice versa,
So that I can use the fields from PowerChurch member data such as "Adult?" and "Hide Email?" without the need to scrub them first before import.

**Comment by seven1m** [comment]
@zarniwoop you might be interested in our [onebody-sync](https://github.com/churchio/onebody-sync/tree/master/powerchurch) project, which includes a script to export data from PowerChurch to CSV for import into OneBody. The script converts "adult" Y/N to "child" N/Y for import into OneBody.

Is this the only boolean field you need to reverse?

**Comment by seven1m** [comment]
I think onebody-sync is the correct approach. Interpreting import fields in reverse seems like a fairly narrow edge case that can be handled easily by an outside script. Adding UI for this would probably just confuse people.
