### ISSUE TITLE
Don't suggest family name change when only difference is "and" vs "&"

### ISSUE THREAD

**Issue by zarniwoop** [churchio/onebody#675]
As a user who imports data that includes family names from our CMS,
I want OneBody not to suggest that the family name be changed to "Dick & Jane Smith" from "Dick and Jane Smith" (since they are semantically the same),
So that I don't inadvertently create a new family record on my next import update when a user made that suggested change and I am importing based on name match.

**Comment by seven1m** [comment]
Done!
