### ISSUE TITLE
Interpret slashes with no numbers as an empty date on import

### ISSUE THREAD

**Issue by zarniwoop** [churchio/onebody#678]
As a PowerChurch user who syncs data using CSV files,
I want OneBody to interpret "/  /" as an empty or null date when it is seen in an importing date field,
So that I do not have to scrub the CSV file after generating from PowerChurch for date fields that have no values (blank birthday or anniversary).

**Comment by seven1m** [comment]
This seems like a reasonable request. I'll see what I can do...
