### ISSUE TITLE
CSV import fails if site setting "Require Strong Password" is set

### ISSUE THREAD

**Issue by TechWilk** [churchio/onebody#680]
Originally reported through [Slack](https://churchio.slack.com/archives/C046A55L0/p1497519213286506), reposted here for visability and to aid tracking:
```
I'm stil getting "password (blank) is too weak" on all the records though
so, looks like you can't have "*Require Strong Password*" set while importing...
If I disable that, it works
```

![error message 'password: is too weak'](https://user-images.githubusercontent.com/9367803/27931788-5f419b30-6293-11e7-8148-b2cbb8d07935.png)

**Comment by seven1m** [comment]
Thanks for the reminder @TechWilk! Should be fixed now.
