### ISSUE TITLE
any? to exists?

### ISSUE THREAD

**Issue by lelelelemon** [churchio/onebody#684]
in app/models/concerns/person/memberships.rb
15      def member_of?(group)
16       memberships.where(group_id: group.id).any?
17      end
any? should be replaced by exists? 
since any? will issue query select count(*), but exists? will issue select 1 as ...

Same situations happen in:
app/models/concerns/person/friend.rb
person.friendship_requests.where(from_id: id, rejected: true).any?
person.friendship_requests.where(from_id: id, rejected: false).any?

**Comment by seven1m** [comment]
Feel free to open a PR with these changes and I'll merge. But I'm not too concerned about it, since the time required to count so few rows is so small anyway.
